### ISSUE TITLE
Report model aggregation not working as documented and a new "Now" key word needed

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#1021]
Something has happened to the Report model and it is not working as documented (also the documentation is out of date).  The simplest aggregation is documented as "Sum of Rain as SumRainfall (mm)" but should now be "Sum of [Weather].Rain as SumRainfall (mm)" but this fails with an error as pasted below.  One theory is that the square brackets have broken the interpretation.  Also there are no tests in the system (they appear to have been lost somehow).

We could also do with a "Now" keyword to assist with the description of the aggregation.  Imagine a daily reporting and  "Sum of [Weather].Rain as from 1-Jan to Now as CumRainfall (mm)" (yes this can be done in the plotting but also useful in the reporting).

If someone is willing to take this on I will assist by updating the documentation and creating some tests and examples.

System.Exception: ERROR in file: C:\ApsimX\Tests\Simulation\AgPastureZones\SlurpZones_v1.apsimx
                      Simulation name: SlurpSingle
                      System.NullReferenceException: Object reference not set to an instance of an object.
                         at APSIM.Shared.Utilities.StringUtilities.ParentName(String name, Char delimiter) in C:\APSIM.Shared\Utilities\StringUtilities.cs:line 460
                         at Models.Core.Apsim.Subscribe(IModel model, String eventNameAndPath, EventHandler handler) in C:\ApsimX\Models\Core\Apsim.cs:line 558
                         at Models.Report.ReportColumn..ctor(String aggregationFunction, String variableName, String columnName, String from, String to, String[] frequenciesFromReport, IModel parentModel) in C:\ApsimX\Models\Report\ReportColumn.cs:line 147
                         at Models.Report.ReportColumn.Create(String descriptor, IModel report, String[] frequenciesFromReport) in C:\ApsimX\Models\Report\ReportColumn.cs:line 232
                         at Models.Report.Report.FindVariableMembers() in C:\ApsimX\Models\Report\Report.cs:line 105
                         at Models.Report.Report.OnSimulationCommencing(Object sender, EventArgs e) in C:\ApsimX\Models\Report\Report.cs:line 83
                         at System.EventHandler.Invoke(Object sender, EventArgs e)
                         at Models.Core.Simulation.StartRun() in C:\ApsimX\Models\Core\Simulation.cs:line 149
                         at Models.Core.Simulation.Run(JobManager jobManager, BackgroundWorker workerThread) in C:\ApsimX\Models\Core\Simulation.cs:line 101
                         at Models.Core.Simulation.Run(JobManager jobManager, BackgroundWorker workerThread) in C:\ApsimX\Models\Core\Simulation.cs:line 127
                         at APSIM.Shared.Utilities.JobManager.Job.Run(JobManager jobManager, BackgroundWorker workerThread) in C:\APSIM.Shared\Utilities\JobManager.cs:line 355

**Comment by sno036** [comment]
This should be merged with #3316
