### ISSUE TITLE
Problem APSIMx files with large number of simulations will not run

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1419]
See attached simulation.  SQL gets ridiculously long!!!!!

[Simulations.zip](https://github.com/APSIMInitiative/ApsimX/files/650703/Simulations.zip)

APSIM.Shared.Utilities.SQLiteException: too many terms in compound SELECT
                         at APSIM.Shared.Utilities.SQLite.Prepare(String query) in C:\APSIM.Shared\Utilities\SQLite.cs:line 482
                         at APSIM.Shared.Utilities.SQLite.ExecuteNonQuery(String query) in C:\APSIM.Shared\Utilities\SQLite.cs:line 300
                         at Models.DataStore.RunQueryWithNoReturnData(String sql) in C:\ApsimX\Models\DataStore.cs:line 569
                         at Models.DataStore.RemoveUnwantedSimulations(Simulations simulationsToKeep, List`1 simulationNamesToBeRun) in C:\ApsimX\Models\DataStore.cs:line 239
                         at Models.Core.Runners.RunOrganiser.Run(JobManager jobManager, BackgroundWorker workerThread) in C:\ApsimX\Models\Core\Runners\RunOrganiser.cs:line 47
                         at APSIM.Shared.Utilities.JobManager.Job.Run(JobManager jobManager, BackgroundWorker workerThread) in C:\APSIM.Shared\Utilities\JobManager.cs:line 445

**Comment by zur003** [comment]
Odd. The contents of the SQLiteException doesn't make sense is this context: we aren't executing a SELECT statement at this point, let alone a compound one. By default, SQLite allows statements to be up to 1 million characters long, so that shouldn't be a problem, either.
For that matter, when I tried running the simulations, I didn't have any database problems, but I did run into an "Out of memory" exception about two-thirds the way through.

**Comment by hut104** [comment]
I didn’t understand what was happening when I saw it, so I reproduced it and showed Dean in a debugger and he told me what to put into a defect report. I then found a way to move on.  Dean’s on holidays now so we can’t ask him.  I’m of no use to you on this one!!!
Sorry, I’m not much help to you.
Neil.
PS Have a good Christmas.
