### ISSUE TITLE
Sowing at the fixed day

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#2636]
In my manager script (Sowing at the fixed day),  I have an item `Crop` which is defined in the script:

```
[Description("Crop")]
public IPlant Crop { get; set; }
````

Then the Properties show a dropdown menu with Value ".Simulations.A.Field.Wheat"

![image](https://user-images.githubusercontent.com/1657381/40692467-59bd733c-63f5-11e8-9fc3-3ff992fadc5a.png)

The error message is

```
Object reference not set to an instance of an object. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Models.PMF.Plant.Sow(String cultivar, Double population, Double depth, Double rowSpacing, Double maxCover, Double budNumber) in Models\Plant\Plant.cs:line 359
   at Models.Script.OnDoManagement(Object sender, EventArgs e) in tmpDCFA.cs:line 41
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Models.Clock.OnDoCommence(Object sender, CommenceArgs e) in Models\Clock.cs:line 219
```

The same codes are working before. It is likely some bugs introduced recently.

**Comment by zur003** [comment]
So far, I haven't been able to reproduce this problem exactly, although it is a bit confusing that the dropdown list for Crop in this situation shows simply "Wheat", but when the user returns to the page they see ".Simulations.Wheat.Field.Wheat" (or something similar, depending on the Zone name).

The line in Plant.cs where the exception was raised would suggest that the Link mechanism didn't connect Clock correctly, which seems a bit odd. I can't account for that.

**Comment by byzheng** [comment]
@zur003  Could you try the attached example?

[test-script.zip](https://github.com/APSIMInitiative/ApsimX/files/2051947/test-script.zip)

**Comment by zur003** [comment]
The error certainly occurs with your example.  I'm not quite sure what's happening, though. It looks like it may be a problem with the "Replacements" mechanism. There is a "Wheat" model there, as well as the one in the base simulation. The script appears to be picking up one that hasn't been fully initialised, but I don't really know how it all works. The base simulation runs correctly if the "Replacements" node is removed.

**Comment by hol430** [comment]
I've just had another user report this error to me. Interestingly, this bug doesn't appear to be present in build 2018.05.29.2633 - the build from 1 day before this issue was reported.

A workaround is to use a link attribute on your crop, e.g. 

`[Link] IPlant maize;`

**Comment by rcichota** [comment]
I came across the problem while writing a manage to cut or graze a crop. Using the same code as sowing (as shown in the top message here) I as get the nice error: "Object reference not set to an instance of an object".  The alternative of using "[Link]", suggested by @hol430 , works but one cannot make it generic (so I need versions of the script to cut each forage species). 
I also tested for whether the use of Replacements was the cause of this issue, after @zur003 . It doesn't seem to be the case, as I get the same error with or without it (I used the Chicory simulation)...

**Comment by hol430** [comment]
Yep this is still an issue - I'll try and have a look at this early next week.

**Comment by byzheng** [comment]
Is this issue fixed? 

We need to run long term simulations, need replacement wheat model and sowing at fixed module. 

Attached an example simulation. 

[test.zip](https://github.com/APSIMInitiative/ApsimX/files/2559854/test.zip)

**Comment by hol430** [comment]
Not fixed yet, it's still on my to-do list. Have you tried the workaround of using a link in your script?
