### ISSUE TITLE
Not all models displaying doco on website

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#3001]
Wheat, SCRUM, Slurp and others are missing
![image](https://user-images.githubusercontent.com/7295858/44816985-124d4500-ac38-11e8-933a-5b24a8eadf8a.png)

**Comment by hol430** [comment]
Yes, for some reason, it's failing to generate the plantain documentation with error message 

```
System.Exception: System.IO.IOException: The file '..\Documentation\PDF\Plantain.pdf' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Script.Execute(MainPresenter mainPresenter) in c:\Users\hol430\AppData\Local\Temp\ApsimX\53z5n5wc.0.cs:line 46
   at UserInterface.Presenters.MainPresenter.ProcessCommandLineArguments(String[] commandLineArguments) in C:\Users\hol430\Documents\ApsimX\ApsimNG\Presenters\MainPresenter.cs:line 754
   at UserInterface.Presenters.MainPresenter.Attach(Object view, String[] commandLineArguments) in C:\Users\hol430\Documents\ApsimX\ApsimNG\Presenters\MainPresenter.cs:line 93
   at UserInterface.UserInterface.Main(String[] args) in C:\Users\hol430\Documents\ApsimX\ApsimNG\Main.cs:line 44
```

Event though I am able to successfully generate plantain documentation locally. As soon as the script encounters an error, it exits without attempting to create documentation for the rest of the models. I will look into it.
