### ISSUE TITLE
Harvesting rule for potato long-term factorials

### ISSUE THREAD

**Issue by JJguri** [APSIMInitiative/ApsimX#3008]
I had an issue related with the harvesting rule using a long-term factorial with potato. Because the harvesting rule was set at maturity, during years were the crop does not achieve this phenological stage, it never is harvested. Therefore, I have added a rule for an alternatively harvesting at fixed date as follow:

if (Phenology.CurrentPhaseName == "Maturity" or Clock.Today == "15-Apr")
            {
                Potato.Harvest();
                Potato.EndCrop();

However, I got the following error:

System.Exception: Unable to compile "Harvesting" ---> System.Exception: ) expected. Line number: 23
Embedded statement cannot be a declaration or labeled statement. Line number: 23
; expected. Line number: 23
Invalid expression term '.'. Line number: 23
; expected. Line number: 23
; expected. Line number: 23
Invalid expression term ')'. Line number: 23
; expected. Line number: 23
   at APSIM.Shared.Utilities.ReflectionUtilities.CompileTextToAssembly(String code, String assemblyFileName)
   at Models.Manager.RebuildScriptModel(List`1 errors)
   --- End of inner exception stack trace ---
   at Models.Manager.set_Code(String value)
   at UserInterface.Presenters.ManagerPresenter.BuildScript()

**Comment by hol430** [comment]
the C# logical or operator is `||`, so your if statement should probably read something like
`if (Phenology.CurrentPhaseName == "Maturity" || Clock.Today == "15-Apr")`

**Comment by hol430** [comment]
What I would recommend doing is adding a DateTime property to your script, and comparing that to `Clock.Today`. To do this, add something along the lines of:

```
[Description("Harvesting Date")]
public DateTime HarvestingDate { get; set; }
```
 just beneath your links. You can then choose April 15 by going to the properties tab and typing 15-Apr into the cell next to Harvesting Date. Then, change your if statement to

```
if (Phenology.CurrentPhaseName == "Maturity" || Clock.Today == HarvestingDate)
```

The advantage of doing it this way is that you can easily change this date from the properties tab. 

When typing the date into the properties tab, you may need to type it in the form dd/mm/yy - I'm not certain. I believe it may depend on your system's date settings. So if you're on Windows, just look in the bottom-right corner of the screen and use the same format that the date is in. In my case, it's dd/mm/yy.

![date](https://user-images.githubusercontent.com/36427516/44887909-d2f32700-ad11-11e8-9d1c-9913f8712364.PNG)

**Comment by JJguri** [comment]
The script is already working, although I need to specify only day and month (dd-mmm) in the properties tab because it is a long-term simulation. I had added this in the script but I am not able to choose this format (dd-mmm) in the properties tab. The system’s date settings of my computer is the same like your computer.
![untitled](https://user-images.githubusercontent.com/41041705/44890609-4bf87b80-ad1e-11e8-8afc-b7feab77a666.jpg)

**Comment by hol430** [comment]
What exactly isn't working? I was also unable to input in dd-mmm format, but putting the date in as dd/mm/yy seemed to work just fine.

**Comment by hol430** [comment]
Never mind, I see the problem. What you can do is use one of our date utility methods, called `CompareDates()`. You will need to change your `HarvestingDate` to be of type string, rather than `DateTime`. 

```
[Description("Harvesting Date (dd-MMM)")]
public string HarvestingDate { get; set; }
```

Then, you can write something like the following:

```
if (Phenology.CurrentPhaseName == "Maturity" || DateUtilities.DatesEqual(HarvestingDate, Clock.Today))
```

**Comment by JJguri** [comment]
In order to harvest the crop once a year, I need to put the harvest date in the dd-mmm instead dd-mm-yyyy format in the properties tab (see below), and I am not able to do that with the current script. Therefore, during years when the crop does not achieve maturity it is not harvested and the HarvestReport is not created. The script works well withouth errors and the simulation run.

![image](https://user-images.githubusercontent.com/41041705/44891888-228f1e00-ad25-11e8-8db1-699847ae0576.png)

**Comment by hol430** [comment]
`EndCrop()` should only be called once. To prevent it being called multiple times, you could check that the crop is alive:

```
if (Potato.IsAlive && (Phenology.CurrentPhaseName == "Maturity" || DateUtilities.DatesEqual(HarvestingDate, Clock.Today)))
```

**Comment by JJguri** [comment]
Everything running!

Just another comment: I have different source of climate data BoM and SILO. I would like to get a column as a part of my report that provide me that information. Can I read this info from the met file? Remember that each weather station to me is a level of a factor "weather" in the factorial, therefore, I am calling the met files from a folder, e.g. [Weather].FileName = Weather\91009.met, with one script.
