### ISSUE TITLE
Error while adding a new model or function

### ISSUE THREAD

**Issue by behnamxa** [APSIMInitiative/ApsimX#3084]
When I try to add a model or function, I receive this error:

### **Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.**

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at APSIM.Shared.Utilities.ReflectionUtilities.GetTypesThatHaveInterface(Type interfaceType) in C:\Users\uqbababa\UQ\07_Repository\ApsimNextGen\APSIM.Shared\Utilities\ReflectionUtilities.cs:line 536
   at Models.Core.Apsim.GetAllowableChildModels(Object parent) in C:\Users\uqbababa\UQ\07_Repository\ApsimNextGen\ApsimX\Models\Core\Apsim.cs:line 590
   at UserInterface.Presenters.AddModelPresenter.Attach(Object model, Object view, ExplorerPresenter explorerPresenter) in C:\Users\uqbababa\UQ\07_Repository\ApsimNextGen\ApsimX\ApsimNG\Presenters\AddModelPresenter.cs:line 43
   at UserInterface.Presenters.ExplorerPresenter.ShowInRightHandPanel(Object model, String viewName, String presenterName) in C:\Users\uqbababa\UQ\07_Repository\ApsimNextGen\ApsimX\ApsimNG\Presenters\ExplorerPresenter.cs:line 760

**Comment by hol430** [comment]
Are you building from source, or using the installed version?

**Comment by behnamxa** [comment]
> Are you building from source, or using the installed version?

**Comment by behnamxa** [comment]
I am building from the source, just after the first pull (no change).

**Comment by hol430** [comment]
I encountered this not too long ago. If you do a pull, does this go away?

If that doesn't fix it, you can also try re-adding MonoMac.dll as a reference to ApsimNG - that is how I fixed it on my machine. To do this, go to the solution explorer on the right, expand ApsimNG, right click on references, select "Add reference", hit browse (near the bottom of this window), navigate to `ApsimX\ApsimNG\Assemblies`, and add MonoMac.dll. 

I'm not sure why this solved the problem, but it did.

**Comment by behnamxa** [comment]
I had read the issue you reported and checked to see if MonoMac.dll was added, and it was. I again followed your instructions, but it did not fix it. Still the same error.

**Comment by hol430** [comment]
Did this stop working recently (perhaps after you did a pull?), or has it been a problem for some time?

**Comment by behnamxa** [comment]
I once tried adding a few items to see how the interface works, without any problem. It was more than 1 month ago. The new problem arose today, when I removed the old files and cloned again (into a new folder).

**Comment by hol430** [comment]
If you ran Apsim today before you pulled down the new version of MonoMac, then maybe it's possible that the GAC is still using the old version of MonoMac... although I'm not certain that would cause this error. I'm not sure if there's an easier way to force it to use the new version, but I would imagine rebooting your PC should do the trick, so I suggest trying that.

**Comment by HamishBrownPFR** [comment]
I have been encountering this error also for the last couple of weeks

**Comment by HamishBrownPFR** [comment]
I have just pulled master, pulled shared, built, put a fresh set of bin files from deployment support into bin, build again and tried to add a function to a PMF model in the UI.  I still get this error.
![image](https://user-images.githubusercontent.com/7295858/45934290-77eee000-bff0-11e8-9bfd-00ce002bba0b.png)

**Comment by hol430** [comment]
Have you tried re-adding MonoMac as a reference in ApsimNG? That solved it for me. MonoMac is located under `ApsimNG/Assemblies`

**Comment by zur003** [comment]
Try setting "Copy Local" to "True" in the properties of the MonoMac reference.

**Comment by hol430** [comment]
Any idea why this is suddenly occurring?

**Comment by HamishBrownPFR** [comment]
Fixes it for me too, thanks guys
