### ISSUE TITLE
Nodule documentation

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#3120]
@HamishBrownPFR In the custom documentation code for the nodule model, we attempt to document a child `DMDemandFunction`:

```
IModel DMDemand = Apsim.Child(this, "DMDemandFunction");
AutoDocumentation.DocumentModel(DMDemand, tags, headingLevel + 1, indent);
```

This `Apsim.Child()` method looks for a child of the model with a specific name. However, if you look at the white clover model's xml, you will find that the nodule does not have a child called called DMDemandFunction.

As far as I can tell, the nodule has a `BiomassRemoval` child called `DMDemands`, and this `DMDemands` had a `DMDemandFunction` a few levels down. I'm unsure if this code should search all children recursively, or if it should actually be searching for a child called `DMDemands`.

**Comment by rcichota** [comment]
@hol430 and @HamishBrownPFR 
I had noticed that while responding to the reviewers comments. and had id fixed (I believe). This is in one of my commits this week, not yet merged, but it passed the tests (though I cannot build the documentation in my PC to really test it)

**Comment by hol430** [comment]
What did you do to fix the problem? Did you just add a `DMDemandFunction` directly under the nodule? If so, the documentation should be working for you.

Might be easier if I pull your down branch and have a look at what's going on.

**Comment by rcichota** [comment]
The appropriate solution was to remove the reference to DMDemandFunction, the code should be searching for DMDemands.  
I (still) cannot create the documentation in my PC, same issue as I related in the email trail. I keep getting the error "Object reference not set to an instance of an object." and this is triggered in the 'Document' method in the organs, during the second pass (which should not occur) the Functions are all null...

**Comment by hol430** [comment]
Have you tried setting "include in documentation" to false on the replacements node?

**Comment by rcichota** [comment]
Ok, just tried that (took me a little while to figure out exactly what you mean, I thought of setting 'include in documentation' only in organs, not the whole Replacements. In any case, both way run a bit further, but still end up with a new error, just this one I cannot figure out where it actually occurs:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at MigraDoc.DocumentObjectModel.Tables.Cells.get_Item(Int32 index)
   at UserInterface.Classes.HtmlToMigraDoc.AddTableColumn(HtmlNode node, DocumentObject section) in C:\ApsimX\ApsimNG\Classes\HtmlToMigraDoc.cs:line 257
   at UserInterface.Classes.HtmlToMigraDoc.ParseNode(HtmlNode node, DocumentObject section, String imagePath) in C:\ApsimX\ApsimNG\Classes\HtmlToMigraDoc.cs:line 90
   at UserInterface.Classes.HtmlToMigraDoc.ConvertNodes(HtmlNodeCollection nodes, DocumentObject section, String imagePath) in C:\ApsimX\ApsimNG\Classes\HtmlToMigraDoc.cs:line 52
   at UserInterface.Classes.HtmlToMigraDoc.ConvertNodes(HtmlNodeCollection nodes, DocumentObject section, String imagePath) in C:\ApsimX\ApsimNG\Classes\HtmlToMigraDoc.cs:line 54
   at UserInterface.Classes.HtmlToMigraDoc.ConvertNodes(HtmlNodeCollection nodes, DocumentObject section, String imagePath) in C:\ApsimX\ApsimNG\Classes\HtmlToMigraDoc.cs:line 54
   at UserInterface.Classes.HtmlToMigraDoc.ConvertNodes(HtmlNodeCollection nodes, DocumentObject section, String imagePath) in C:\ApsimX\ApsimNG\Classes\HtmlToMigraDoc.cs:line 54
   at UserInterface.Classes.HtmlToMigraDoc.Convert(String html, Section section, String imagePath) in C:\ApsimX\ApsimNG\Classes\HtmlToMigraDoc.cs:line 37
   at UserInterface.Commands.ExportNodeCommand.AddFormattedParagraphToSection(Section section, Paragraph paragraph) in C:\ApsimX\ApsimNG\Commands\ExportNodeCommand.cs:line 708
   at UserInterface.Commands.ExportNodeCommand.TagsToMigraDoc(Section section, List`1 tags, String workingDirectory) in C:\ApsimX\ApsimNG\Commands\ExportNodeCommand.cs:line 600
   at UserInterface.Commands.ExportNodeCommand.DoExportPDF(String modelNameToExport) in C:\ApsimX\ApsimNG\Commands\ExportNodeCommand.cs:line 190
   at UserInterface.Commands.ExportNodeCommand.Do(CommandHistory CommandHistory) in C:\ApsimX\ApsimNG\Commands\ExportNodeCommand.cs:line 68
   at UserInterface.CommandHistory.Add(ICommand command, Boolean execute) in C:\ApsimX\ApsimNG\CommandHistory.cs:line 103
   at UserInterface.Presenters.ContextMenu.CreateDocumentation(Object sender, EventArgs e) in C:\ApsimX\ApsimNG\Menus\ContextMenu.cs:line 603

**Comment by hol430** [comment]
I believe this is caused by the formatting of the table in the white clover apsimx file, around line 80. I am looking into it.

**Comment by rcichota** [comment]
Ok, that is a new table I added as per request of one of the reviewers. It shows all right in the UI, though very simple formatting. If it is too hard to solve now, I could get read of it, or re-write it not using the table formatting...

**Comment by rcichota** [comment]
Removing the table at line 80 allows me to create the pdf file. I think i will just re-write it as a non-formatted table...

**Comment by hol430** [comment]
The real problem behind this issue is that the autodocs cannot generate a MigraDoc/PdfSharp table from the table given below. The markdown to HTML works fine - it displays perfectly in the memo (HTML) view - but bad stuff happens when we go the next step.

```
The default values for the fractions (%) to be removed or transferred to residue are shown below, they are also listed in the description of each organ:

|Organ      |      |   Harvest         |  |    Cut            |  |   Graze           |  |   Prune           |  |
|-----------|------|-------------------|--|-------------------|--|-------------------|--|-------------------|--|
|           |      | ToRemove | ToResidue | ToRemove | ToResidue | ToRemove | ToResidue | ToRemove | ToResidue |
|Leaf       | Live |    10    |    10     |    80    |     0     |    70    |    10     |     0    |    20     |
|           | Dead |    10    |    10     |    20    |     0     |    10    |    20     |     0    |    20     |
|Petiole    | Live |    10    |    10     |    50    |     0     |    50    |    10     |     0    |    20     |
|           | Dead |    20    |    10     |    50    |     0     |    20    |    10     |     0    |    20     |
|Stolon     | Live |     0    |     0     |     0    |     0     |    20    |    10     |     0    |    20     |
|           | Dead |     0    |     0     |     0    |     0     |     0    |    20     |     0    |    20     |
|Infloresc. | Live |    80    |    10     |    80    |     0     |    60    |    20     |     0    |    20     |
|           | Dead |    80    |    10     |    60    |     0     |    20    |    20     |     0    |    20     |
|Nodule     | Live |     0    |     2     |     0    |     3     |     0    |     3     |     0    |     2     |
|           | Dead |     0    |     0     |     0    |     0     |     0    |     0     |     0    |     0     |
|Taproot    | Live |     0    |    10     |     0    |    10     |     0    |    10     |     0    |    10     |
|           | Dead |     0    |     0     |     0    |     0     |     0    |     0     |     0    |     0     |
|Root       | Live |     0    |     5     |     0    |     5     |     0    |     5     |     0    |     5     |
|           | Dead |     0    |     0     |     0    |     0     |     0    |     0     |     0    |     0     |
```

**Comment by hol430** [comment]
I still see the occasional null reference exception in the nodule documentation (e.g. on line 629) - it's probably worth throwing some null checks in there. I'll try to get a pull request up for this later today.
