### ISSUE TITLE
APSIM cannot detect column headers in an Excel met file

### ISSUE THREAD

**Issue by behnamxa** [APSIMInitiative/ApsimX#3299]
When I use an Excel file for weather data (and this is my first time), I receive the following error and I cannot figure out what causes this. 

```
System.NullReferenceException occurred
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=APSIM.Shared
  StackTrace:
   at APSIM.Shared.Utilities.ApsimTextFile.SeekToDate(DateTime date) in C:\Users\uqbababa\UQ\07_Repository\ApsimNextGen\APSIM.Shared\Utilities\ApsimTextFile.cs:line 746
   at Models.Weather.OnDoWeather(Object sender, EventArgs e) in C:\Users\uqbababa\UQ\07_Repository\ApsimNextGen\ApsimX\Models\Weather\Weather.cs:line 415
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Models.Clock.OnDoCommence(Object sender, CommenceArgs e) in C:\Users\uqbababa\UQ\07_Repository\ApsimNextGen\ApsimX\Models\Clock.cs:line 220
```

I followed [this instruction](https://apsimnextgeneration.netlify.com/usage/usingexcelforweatherdata/) to create the met file. It seems APSIM cannot detect column headers:

![image](https://user-images.githubusercontent.com/39573622/48680897-e0ba9900-ebea-11e8-948a-9ef9bb7a3251.png)

I attach the met and APSIM file, in case someone could test it.
[ADAP.zip](https://github.com/APSIMInitiative/ApsimX/files/2593424/ADAP.zip)

**Comment by hol430** [comment]
Looks like a bug - not user error. Will look into it.

**Comment by behnamxa** [comment]
Thanks Drew. I shifted to text files again. Cheers.
