### ISSUE TITLE
Trouble importing soil files from the stack

### ISSUE THREAD

**Issue by mpandreucci** [APSIMInitiative/ApsimX#3462]
Hi.
When I try to import a soil file from the Stack I get this error message:
Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path 'SoilType', line 6, position 15.
   at Newtonsoft.Json.JsonReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Models.Core.ApsimFile.FileFormat.ReadFromString[T](String st, List`1& creationExceptions, String fileName) in C:\Work\ApsimX\Models\Core\ApsimFile\FileFormat.cs:line 89
   at Models.Core.ApsimFile.Structure.Add(String st, IModel parent) in C:\Work\ApsimX\Models\Core\ApsimFile\Structure.cs:line 43
   at UserInterface.Commands.AddModelCommand.Do(CommandHistory commandHistory) in C:\Work\ApsimX\ApsimNG\Commands\AddModelCommand.cs:line 55

Is there anything I should be doing to make this work?

**Comment by hol430** [comment]
What is the Stack?

**Comment by mpandreucci** [comment]
Hi Drew.
It is the wise database for soils. 
https://www.apsim.info/TheStack/The_Stack_Library.kml

**Comment by mpandreucci** [comment]
Hi Drew.
Did you have any luck with this problem? I'm still getting the same error message.
Thanks,
Mariana

**Comment by hol430** [comment]
I can successfully paste the soil which @hol353 uploaded...I'm still not sure what to do with the stack library which you provided. Are you on the latest version of apsim?

**Comment by mpandreucci** [comment]
Hi Drew.
Yes, I always update everything.
The soils from the stack are working now. Thank you very much for that.
