### ISSUE TITLE
Race condition in Morris/R component

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#3678]
This popped up in one of the recent jenkins builds:

```
Commencing simulations...
ERRORS FOUND!!
Error in file: C:\Jenkins\workspace\PullRequest_v2\ApsimX\Examples\Tutorials\Sensitivity_MorrisMethod.apsimx /RunTests
RScript executable: C:\Program Files\R\R-3.5.1\bin\x64\Rscript.exe
[1] "Installing package sensitivity to location C:/Users/scoop/AppData/Local/Temp/dabedbf2-e5c3-4af7-80cf-3492a466712e"
package 'sensitivity' successfully unpacked and MD5 sums checked
The downloaded binary packages are in
	C:\Users\scoop\AppData\Local\Temp\RtmpS6FhwW\downloaded_packages

File: Sensitivity_MorrisMethod, Simulation MorrisMethodExampleSimulation1 has commenced.
...
File: Sensitivity_MorrisMethod, Simulation MorrisMethodExampleSimulation96 complete. Time: 20.09 sec
RScript executable: C:\Program Files\R\R-3.5.1\bin\x64\Rscript.exe
[1] "Installing package sensitivity to location C:/Users/scoop/AppData/Local/Temp/c3d64511-1963-46ce-9ccd-fab04a1d3c17"
package 'sensitivity' successfully unpacked and MD5 sums checked
The downloaded binary packages are in
	C:\Users\scoop\AppData\Local\Temp\RtmpEvqdkG\downloaded_packages

ERRORS FOUND!!
System.Exception: Error from R: 
Warning message:
package 'sensitivity' was built under R version 3.5.3 
Error in `$<-.data.frame`(`*tmp*`, "path", value = 1:25) : 
  replacement has 25 rows, data has 24
Calls: $<- -> $<-.data.frame
Execution halted

Script:
library('sensitivity')
params <- c("SOC","Load","DUL")
apsimMorris<-morris(model=NULL
 ,params #string vector of parameter names
 ,25 #no of paths within the total parameter space
 ,design=list(type="oat",levels=11,grid.jump=5)
 ,binf=c(1,100,0.2) #min for each parameter
 ,bsup=c(10,1000,0.4) #max for each parameter
 ,scale=T
 )
apsimMorris$X <- read.csv("C:/Users/scoop/AppData/Local/Temp/parameters9e683d36-ec74-4c73-b526-54055a407ded.csv")
values = read.csv("C:/Users/scoop/AppData/Local/Temp/apsimvariable9e683d36-ec74-4c73-b526-54055a407ded.csv")
allEE <- data.frame()
allStats <- data.frame()
for (columnName in colnames(values))
{
 apsimMorris$y <- values[[columnName]]
 tell(apsimMorris)
 ee <- data.frame(apsimMorris$ee)
 ee$variable <- columnName
 ee$path <- c(1:25)
 allEE <- rbind(allEE, ee)
 mu <- apply(apsimMorris$ee, 2, mean)
 mustar <- apply(apsimMorris$ee, 2, function(x) mean(abs(x)))
 sigma <- apply(apsimMorris$ee, 2, sd)
 stats <- data.frame(mu, mustar, sigma)
 stats$param <- params
 stats$variable <- columnName
 allStats <- rbind(allStats, stats)
}
write.csv(allEE,"C:/Users/scoop/AppData/Local/Temp/ee9e683d36-ec74-4c73-b526-54055a407ded.csv", row.names=FALSE)
write.csv(allStats, "C:/Users/scoop/AppData/Local/Temp/stats9e683d36-ec74-4c73-b526-54055a407ded.csv", row.names=FALSE)

   at Models.Utilities.R.Run(String fileName, String arguments, Boolean throwOnError) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Utilities\R.cs:line 160
   at Models.Utilities.R.RunToTable(String fileName, String arguments) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Utilities\R.cs:line 172
   at Models.Morris.RunRPostSimulation(DataTable predictedValues, DataTable& eeDataRaw, DataTable& statsDataRaw) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Sensitivity\Morris.cs:line 537
   at Models.Morris.Run(IDataStore dataStore) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Sensitivity\Morris.cs:line 383
   at Models.Core.Runners.RunOrganiser.RunPostSimulationTools(IModel rootModel, IDataStore storage) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Core\Runners\RunOrganiser.cs:line 154
   at Models.Core.Runners.RunOrganiser.Completed() in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Core\Runners\RunOrganiser.cs:line 114
   at APSIM.Shared.Utilities.JobRunnerAsync.JobRunnerThread(IJobManager jobs, Int32 numberOfTasksToUse) in C:\Jenkins\workspace\PullRequest_v2\APSIM.Shared\Utilities\JobRunnerAsync.cs:line 109
----------------------------------------------

Finished running simulations. Duration 318.34 sec.


----------------------------------------------
```

**Comment by hol430** [comment]
Closing this - I think it's been fixed.
