### ISSUE TITLE
'Experiment' object does not show the list of factorial experiments

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#3766]
When I select an **Experiment** object, it does not show the list of the combinations of factors anymore and I get this error:

`Method not found: 'Void Gtk.Builder.Autoconnect(System.Object)'.`

![image](https://user-images.githubusercontent.com/39573622/56330319-e385de00-61ca-11e9-81d2-7ced2aed4c7e.png)

**Comment by hol430** [comment]
I wonder if apsim has found the wrong version of gtk-sharp.dll. In the visual studio debug output window, there should be a line like this:

```
'ApsimNG.exe' (CLR v4.0.30319: ApsimNG.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\gtk-sharp\v4.0_2.12.0.0__35e10195dab3c99f\gtk-sharp.dll'. Symbol loading disabled by Include/Exclude setting.
```

You can search for 'gtk-sharp' (without the quotes) in the output window. What does this line say for you? If you can't find it, just paste the entire contents of the output window and I'll have a look.

**Comment by BenAbabaei** [comment]
Is this what you mean by **output window**:

```
System.MissingMethodException: Method not found: 'Void Gtk.Builder.Autoconnect(System.Object)'.
   at UserInterface.Views.ExperimentView..ctor(ViewBase owner)
```

**Comment by BenAbabaei** [comment]
`
'ApsimNG.exe' (CLR v4.0.30319: ApsimNG.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\gtk-sharp\v4.0_2.12.0.0__35e10195dab3c99f\gtk-sharp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
`

**Comment by hol430** [comment]
Yep, that's the line I was thinking of. What happens if you rename that file:

```
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\gtk-sharp\v4.0_2.12.0.0__35e10195dab3c99f\gtk-sharp.dll
```

e.g. rename it to gtk-sharp.dll.bak. Apsim might then use the gtk-sharp.dll which we copy into the bin directory.

**Comment by BenAbabaei** [comment]
I got this exception:

```
System.MissingMethodException occurred
  HResult=0x80131513
  Message=Method not found: 'Void GLib.Log.Write(System.String, GLib.LogLevelFlags, System.String, System.Object[])'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Gtk.Application.AssertMainThread()
   at Gtk.Settings.SetLongProperty(String name, Int64 v_long, String origin)
   at UserInterface.UserInterface.Main(String[] args) in C:\Users\uqbababa\UQ\07_Repository\ApsimNextGen\ApsimX\ApsimNG\Main.cs:line 18
```

**Comment by hol430** [comment]
Have you copied the files from DeploymentSupport/Windows/Bin64/ into Bin/?

**Comment by BenAbabaei** [comment]
Yes. I didn't change anything. Just updated to the latest commits.

**Comment by hol430** [comment]
Can you find this line again in your output window? Where is it finding the dll now that you have renamed the old one?

```
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\gtk-sharp\v4.0_2.12.0.0__35e10195dab3c99f\gtk-sharp.dll
```

**Comment by BenAbabaei** [comment]
`
'ApsimNG.exe' (CLR v4.0.30319: ApsimNG.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\gtk-sharp\v4.0_2.12.0.0__35e10195dab3c99f\gtk-sharp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
`

And the whole output:

```
'ApsimNG.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ApsimNG.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\uqbababa\UQ\07_Repository\ApsimNextGen\ApsimX\Bin\ApsimNG.exe'. Symbols loaded.
'ApsimNG.exe' (CLR v4.0.30319: ApsimNG.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ApsimNG.exe' (CLR v4.0.30319: ApsimNG.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ApsimNG.exe' (CLR v4.0.30319: ApsimNG.exe): Loaded 'C:\Users\uqbababa\UQ\07_Repository\ApsimNextGen\ApsimX\Bin\Models.exe'. Symbols loaded.
'ApsimNG.exe' (CLR v4.0.30319: ApsimNG.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\gtk-sharp\v4.0_2.12.0.0__35e10195dab3c99f\gtk-sharp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ApsimNG.exe' (CLR v4.0.30319: ApsimNG.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\glib-sharp\v4.0_2.12.0.0__35e10195dab3c99f\glib-sharp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ApsimNG.exe' (CLR v4.0.30319: ApsimNG.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\atk-sharp\v4.0_2.12.0.0__35e10195dab3c99f\atk-sharp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ApsimNG.exe' (CLR v4.0.30319: ApsimNG.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\gdk-sharp\v4.0_2.12.0.0__35e10195dab3c99f\gdk-sharp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ApsimNG.exe' (CLR v4.0.30319: ApsimNG.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\pango-sharp\v4.0_2.12.0.0__35e10195dab3c99f\pango-sharp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ApsimNG.exe' (CLR v4.0.30319: ApsimNG.exe): Loaded 'C:\Users\uqbababa\UQ\07_Repository\ApsimNextGen\ApsimX\Bin\APSIM.Shared.dll'. Symbols loaded.
'ApsimNG.exe' (CLR v4.0.30319: ApsimNG.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ApsimNG.exe' (CLR v4.0.30319: ApsimNG.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ApsimNG.exe' (CLR v4.0.30319: ApsimNG.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ApsimNG.exe' (CLR v4.0.30319: ApsimNG.exe): Loaded 'Microsoft.GeneratedCode'. 

```

**Comment by hol430** [comment]
@hol353 out of curiosity, what does this line of code do? This line seems to have appeared during the recent refactor of experiment view, but none of the other views which use glade files seem to call this method.

```csharp
builder.Autoconnect(this);
```

**Comment by hol430** [comment]
@BenAbabaei did you rename or move that gtk-sharp.dll? We don't want a file called gtk-sharp.dll to exist in that folder, but .net still seems to be finding a file there.

**Comment by BenAbabaei** [comment]
@hol430 When I rename that file, I got this exception:

```
System.MissingMethodException occurred
  HResult=0x80131513
  Message=Method not found: 'Void GLib.Log.Write(System.String, GLib.LogLevelFlags, System.String, System.Object[])'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Gtk.Application.AssertMainThread()
   at Gtk.Settings.SetLongProperty(String name, Int64 v_long, String origin)
   at UserInterface.UserInterface.Main(String[] args) in C:\Users\uqbababa\UQ\07_Repository\ApsimNextGen\ApsimX\ApsimNG\Main.cs:line 18
```

**Comment by hol430** [comment]
What was in the debug output window when you get that exception?

**Comment by BenAbabaei** [comment]
```
'ApsimNG.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ApsimNG.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\uqbababa\UQ\07_Repository\ApsimNextGen\ApsimX\Bin\ApsimNG.exe'. Symbols loaded.
'ApsimNG.exe' (CLR v4.0.30319: ApsimNG.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ApsimNG.exe' (CLR v4.0.30319: ApsimNG.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ApsimNG.exe' (CLR v4.0.30319: ApsimNG.exe): Loaded 'C:\Users\uqbababa\UQ\07_Repository\ApsimNextGen\ApsimX\Bin\Models.exe'. Symbols loaded.
'ApsimNG.exe' (CLR v4.0.30319: ApsimNG.exe): Loaded 'C:\Users\uqbababa\UQ\07_Repository\ApsimNextGen\ApsimX\Bin\gtk-sharp.dll'. Module was built without symbols.
'ApsimNG.exe' (CLR v4.0.30319: ApsimNG.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\glib-sharp\v4.0_2.12.0.0__35e10195dab3c99f\glib-sharp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ApsimNG.exe' (CLR v4.0.30319: ApsimNG.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\atk-sharp\v4.0_2.12.0.0__35e10195dab3c99f\atk-sharp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ApsimNG.exe' (CLR v4.0.30319: ApsimNG.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\gdk-sharp\v4.0_2.12.0.0__35e10195dab3c99f\gdk-sharp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'System.MissingMethodException' in gtk-sharp.dll
An unhandled exception of type 'System.MissingMethodException' occurred in gtk-sharp.dll
Method not found: 'Void GLib.Log.Write(System.String, GLib.LogLevelFlags, System.String, System.Object[])'.
```

**Comment by hol430** [comment]
Can you move or rename those other files as well?

```
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\glib-sharp\v4.0_2.12.0.0__35e10195dab3c99f\glib-sharp.dll
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\atk-sharp\v4.0_2.12.0.0__35e10195dab3c99f\atk-sharp.dll
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\gdk-sharp\v4.0_2.12.0.0__35e10195dab3c99f\gdk-sharp.dll
```

If this doesn't work, I think I'll just see if I can remove that line of code from the experiment view which was causing you problems in the first place.

**Comment by BenAbabaei** [comment]
I did. When I open the interface and try to load an APSIM file (no matter which one), the interface is closed without an exception.

**Comment by hol430** [comment]
Immediately after it crashes, there should be a file ApsimX/Bin/errors.txt. Can you paste the contents of this file? Apsim deletes this whenever it starts up, so you will need to check it immediately after apsim crashes.

If you can't find the errors.txt then yeah, change those dll filenames back to the way they were, and I'll just remove this line of code (or wrap it in a try-catch at the very least).

**Comment by BenAbabaei** [comment]
Yeah, I searched for it before your comment. There is no such a file in Bin. Sorry.

**Comment by hol430** [comment]
No worries. I'm not sure why you're getting the missing method exception. It seems like the easiest solution will be to remove the call to the missing method, as I'm pretty sure it's not needed in any case.

You'll probably need to reset those .dll filenames. That should get apsim (mostly!) working again.

**Comment by zur003** [comment]
Get rid of the call to AutoConnect. I remember having this problem when I was first setting up Gtk stuff. AutoConnect can be used to automatically connect Gtk# objects with controls, but it's much safer to use GetObject to explicitly make these associations. It's a problem because only relatively recent versions of version 2 Gtk# support this call (version 3 would be a different story). Many people will already have Gtk# DLLs in their assembly caches, and if they have a slightly older version that gets pulled in, you'll see this error.
