### ISSUE TITLE
Lucerne prototype fail to run

### ISSUE THREAD

**Issue by frank0434** [APSIMInitiative/ApsimX#4252]
Hi, @HamishBrownPFR & @Xiumei2017 
The lucerne model keeps complaining about the following exception. 
```
System.Exception: Encountered an error while running test Test ---> System.Exception: Test failed. R2 is below threshold. R2=0.147874389360806
   at Models.Script.Run() in c:\Users\cflfcl\AppData\Local\Temp\ApsimXManager627b6ffd-3a16-49b9-86cd-d81934fa28b7.cs:line 21
   at Models.Core.Run.SimulationGroup.RunTests() in C:\Data\latest_apsimx\ApsimX\Models\Core\Run\SimulationGroup.cs:line 292
   --- End of inner exception stack trace ---
```
Wondering what is this test for? 

I currently modified the `R2 < 0.59` (The default value) to `R2 < 0`.
Simulation can run ok but I reckon it's probably inappropriate. 

Thanks in advance for any instruction.

**Comment by frank0434** [comment]
test failed but simulation has done. 
close the issue.
