### ISSUE TITLE
Azure functionality is broken

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#4340]
From @sno036:

> I just tied this with Azure and got an error. It might be that the easiest if I supplied a Azure creds to someone who knows what they are doing so they can test. Just let me know who.
>
> System.IO.IOException
HResult=0x80070020
Message=The process cannot access the file 'C:\Users\snowv\OneDrive - AgResearch\Desktop\Temp\TestAzure.db' because it is being used by another process.
Source=mscorlib
StackTrace:
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
at System.IO.Compression.ZipFileExtensions.DoCreateEntryFromFile(ZipArchive destination, String sourceFileName, String entryName, Nullable1 compressionLevel) at System.IO.Compression.ZipFile.DoCreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, Nullable1 compressionLevel, Boolean includeBaseDirectory, Encoding entryNameEncoding)
at System.IO.Compression.ZipFile.CreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, CompressionLevel compressionLevel, Boolean includeBaseDirectory)
at UserInterface.Presenters.NewAzureJobPresenter.SubmitJob_DoWork(Object o, DoWorkEventArgs e) in C:\aaUnderVC\apsimNextGen\ApsimNG\Presenters\NewAzureJobPresenter.cs:line 338
at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

@hol353 on a side note, do you think we should add some unit tests for this Azure stuff? This would require us to purchase a small Azure VM which we can use for simple jobs on Jenkins but I doubt it would cost much. Would probably also want to do the same for other platforms as we add them (ie aws, google compute, etc).

**Comment by hol353** [comment]
Yep, good idea.

**Comment by hol430** [comment]
@sno036 I see that you ran an azure job in August with 260 sims called PaddockGrid50test. Did this actually....work? If so, were you using a very old version of apsim?

**Comment by hol430** [comment]
@sno036 Val do you still use the 'auto download results' and 'summarise results' features? I'm not sure how useful these are since the jobs on Azure will typically be long running jobs. I'm also considering moving the status info into the status panel (the place where the progress bar and errors are normally shown). Any preferences here?

![image](https://user-images.githubusercontent.com/36427516/69926510-7b3d0000-1500-11ea-9868-0a4356e29079.png)

**Comment by hol430** [comment]
@sno036 @hol353 the run on cloud feature should be working better now. There are still a few outstanding issues (send email upon completion still doesn't work) but you should at least be able to run stuff now. I suspect that the sensitivity analysis components also won't work properly - the individual simulations will run, but the post-simulation analysis won't happen. The ideal fix for this would be to implement a new job runner (or is it called job manager now?) which could work similarly to the multi process job runner, and would replace azure-apsim.exe (which is quite primitive and inflexible).

**Comment by sno036** [comment]
Thanks @hol430 - should look into this at some point but not the highest priority right now - good to know that the basic part if working again!

**Comment by hol353** [comment]
I have

- cchanged this so that weather files can exist in directories other than where the .apsimx file is located. 
- cleaned up a lot of the GUI options that aren't really needed. Makes it simpler to use.

The original error "The process cannot access the file 'C:\Users\snowv\OneDrive - AgResearch\Desktop\Temp\TestAzure.db' because it is being used by another process." could be caused by OneDrive having a file locked because it was syncing it at the time. May be best to put results somewhere else.
