### ISSUE TITLE
Error from met file in TropPasture simulation

### ISSUE THREAD

**Issue by mpandreucci** [APSIMInitiative/ApsimX#4881]
[TropPasture.zip](https://github.com/APSIMInitiative/ApsimX/files/4314702/TropPasture.zip)
@hol353  This is the simulation with the error message about the weather file. I'm not sure what is going on. Could you please help? Thanks a lot

This is the error message

System.Exception: ERROR in file: C:\apsimXWorking\Lucas\TropPastureNitro.apsimx
Simulation name: ExpNAmount20
System.IndexOutOfRangeException: There is no row at position 14396.
   at System.Data.RBTree`1.GetNodeByIndex(Int32 userIndex)
   at System.Data.DataRowCollection.get_Item(Int32 index)
   at APSIM.Shared.Utilities.ApsimTextFile.GetNextLineOfData() in C:\Work\ApsimX\APSIM.Shared\Utilities\ApsimTextFile.cs:line 796
   at Models.Weather.OnDoWeather(Object sender, EventArgs e) in C:\Work\ApsimX\Models\Weather\Weather.cs:line 490
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Models.Clock.OnDoCommence(Object sender, CommenceArgs e) in C:\Work\ApsimX\Models\Clock.cs:line 292
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Work\ApsimX\Models\Core\Simulation.cs:line 237 ---> System.IndexOutOfRangeException: There is no row at position 14396.
   at System.Data.RBTree`1.GetNodeByIndex(Int32 userIndex)
   at System.Data.DataRowCollection.get_Item(Int32 index)
   at APSIM.Shared.Utilities.ApsimTextFile.GetNextLineOfData() in C:\Work\ApsimX\APSIM.Shared\Utilities\ApsimTextFile.cs:line 796
   at Models.Weather.OnDoWeather(Object sender, EventArgs e) in C:\Work\ApsimX\Models\Weather\Weather.cs:line 490
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Models.Clock.OnDoCommence(Object sender, CommenceArgs e) in C:\Work\ApsimX\Models\Clock.cs:line 292
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Work\ApsimX\Models\Core\Simulation.cs:line 237
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Work\ApsimX\Models\Core\Simulation.cs:line 249
   at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in C:\Work\ApsimX\Models\Core\Run\SimulationDescription.cs:line 100
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in C:\Work\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 161

**Comment by hol430** [comment]
Looks like the end date of the simulation is 31 December 2019 but the met data only goes to about halfway through 2019 (doy 151.

**Comment by mpandreucci** [comment]
Oh yeah, I think I got sent the wrong file from Lucas.
I'll check with him. Thanks a lot Drew, sorry for that
