### ISSUE TITLE
Cannot open the attached .apsimx file

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#4924]
1.	I can’t open the output.apsimx file. The error message is:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Models.Core.ApsimFile.Converter.UpgradeToVersion87(JObject root, String fileName)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Models.Core.ApsimFile.Converter.DoConvert(String st, Int32 toVersion, String fileName)
   at Models.Core.ApsimFile.FileFormat.ReadFromString[T](String st, List`1& creationExceptions, String fileName)
   at Models.Core.ApsimFile.FileFormat.ReadFromFile[T](String fileName, List`1& creationExceptions)
   at UserInterface.Presenters.MainPresenter.OpenApsimXFileInTab(String fileName, Boolean onLeftTabControl)

[output.zip](https://github.com/APSIMInitiative/ApsimX/files/4340028/output.zip)

**Comment by hol353** [comment]
@hol430 Can you fix this one for Phil?
