### ISSUE TITLE
"Could not open assembly" when trying to open a file

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#4981]
An unhelpful error message is provided when opening the attached simulation file.  The error message is:
Could not load assembly 'ApsimXManager16cef9df-cc6d-4026-83c9-1fbfa7bbf060'.

=====
The actuall error is
Newtonsoft.Json.JsonSerializationException: Error resolving type specified in JSON 'Models.Script, ApsimXManager16cef9df-cc6d-4026-83c9-1fbfa7bbf060'. Path 'Children[1].Children[0].Children[0].$type', line 46, position 89. ---> Newtonsoft.Json.JsonSerializationException: Could not load assembly 'ApsimXManager16cef9df-cc6d-4026-83c9-1fbfa7bbf060'.
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey(StructMultiKey`2 typeNameKey)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.BindToType(String assemblyName, String typeName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
   --- End of inner exception stack trace ---
![image](https://user-images.githubusercontent.com/11881178/77977011-dad9d980-7341-11ea-9742-6f9f5bc5359f.png)

[GliricidiaTransect.zip](https://github.com/APSIMInitiative/ApsimX/files/4406204/GliricidiaTransect.zip)

**Comment by hol430** [comment]
This seems to be caused by placing a manager script under replacements. When saving the file, the manager object's Script child will be serialized to the .apsimx file, and its type cannot be resolved when reopening the file.
