### ISSUE TITLE
Supplement library isn't thread safe

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#5377]
I just got a bunch of errors from Jenkins in code I didn't change - see errors at bottom.

If you look at lines around GrazSupp.cs:line 773:

```c#
for (int idx = 0; idx < SupplementLibrary.DefaultSuppConsts.Count; idx++)
{
    string suppName = SupplementLibrary.DefaultSuppConsts[idx].Name.ToUpper();
    ...
}
```
The static property SupplementLibrary.DefaultSuppConsts is used on the for loop line as well as inside the for loop. The exception was thrown inside the for loop. The only way this can happen is if some other thread changed DefaultSuppConsts sometime between the 'for' line and the inner 'suppName = ' line. This SupplementLibrary.DefaultSuppConst property is implemented as:

```c#
        public static SupplementLibrary DefaultSuppConsts
        {
            get
            {
                if (GDefSupp == null)
                {
                    GDefSupp = new SupplementLibrary();
                    SetupDefaultSupplements();
                }
                return GDefSupp;
            }
        }
```
Where there are more than one thread accessing this property there can potentially be problems due to the lack of locks. I think this is what happened on Jenkins (although I thought Jenkins ran things multiprocess rather then multithreaded).

```
----------------------------------------------

System.Exception: Error in file:C:\Jenkins\workspace\PullRequest_v2\ApsimX\Tests\Simulation\DairyFarmManager\PlantainGrazing.apsimx ---> System.NullReferenceException: Object reference not set to an instance of an object.

   at Models.GrazPlan.FoodSupplement.ParseText(String suppSt, Boolean nameOnly) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Grazplan\GrazSupp.cs:line 773

   at Models.GrazPlan.FoodSupplement..ctor(String suppSt) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Grazplan\GrazSupp.cs:line 279

   at Models.GrazPlan.SupplementModel.AddToStore(Double suppKg, String suppName, Int32 roughage, Double dmp, Double dmd, Double medm, Double cp, Double dg, Double ee, Double adip2cp, Double phos, Double sulf, Double ashAlk, Double maxPass) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Grazplan\Supplement.cs:line 241

   at Models.GrazPlan.SupplementModel..ctor() in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Grazplan\Supplement.cs:line 66

   at Models.GrazPlan.Supplement..ctor() in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Grazplan\Supplement.cs:line 826

   at CreateModels.GrazPlan.Supplement()

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)

   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)

   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)

   at Models.Core.ApsimFile.FileFormat.ReadFromString[T](String st, List`1& creationExceptions, String fileName) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Core\ApsimFile\FileFormat.cs:line 90

   at Models.Core.ApsimFile.FileFormat.ReadFromFile[T](String fileName, List`1& creationExceptions) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Core\ApsimFile\FileFormat.cs:line 66

   at Models.Core.Run.SimulationGroup.Initialise() in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Core\Run\SimulationGroup.cs:line 183

   --- End of inner exception stack trace ---

----------------------------------------------

System.Exception: Error in file:C:\Jenkins\workspace\PullRequest_v2\ApsimX\Tests\Simulation\DairyFarmManager\SimpleRotation.apsimx ---> System.NullReferenceException: Object reference not set to an instance of an object.

   at Models.GrazPlan.FoodSupplement.ParseText(String suppSt, Boolean nameOnly) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Grazplan\GrazSupp.cs:line 773

   at Models.GrazPlan.FoodSupplement..ctor(String suppSt) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Grazplan\GrazSupp.cs:line 279

   at Models.GrazPlan.SupplementModel.AddToStore(Double suppKg, String suppName, Int32 roughage, Double dmp, Double dmd, Double medm, Double cp, Double dg, Double ee, Double adip2cp, Double phos, Double sulf, Double ashAlk, Double maxPass) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Grazplan\Supplement.cs:line 241

   at Models.GrazPlan.SupplementModel..ctor() in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Grazplan\Supplement.cs:line 66

   at Models.GrazPlan.Supplement..ctor() in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Grazplan\Supplement.cs:line 826

   at CreateModels.GrazPlan.Supplement()

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)

   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)

   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)

   at Models.Core.ApsimFile.FileFormat.ReadFromString[T](String st, List`1& creationExceptions, String fileName) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Core\ApsimFile\FileFormat.cs:line 90

   at Models.Core.ApsimFile.FileFormat.ReadFromFile[T](String fileName, List`1& creationExceptions) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Core\ApsimFile\FileFormat.cs:line 66

   at Models.Core.Run.SimulationGroup.Initialise() in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Core\Run\SimulationGroup.cs:line 183

   --- End of inner exception stack trace ---

----------------------------------------------

System.Exception: Error in file:C:\Jenkins\workspace\PullRequest_v2\ApsimX\Tests\UnderReview\Stock\Stock.apsimx ---> System.NullReferenceException: Object reference not set to an instance of an object.

   at Models.GrazPlan.FoodSupplement.ParseText(String suppSt, Boolean nameOnly) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Grazplan\GrazSupp.cs:line 773

   at Models.GrazPlan.FoodSupplement..ctor(String suppSt) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Grazplan\GrazSupp.cs:line 279

   at Models.GrazPlan.SupplementModel.AddToStore(Double suppKg, String suppName, Int32 roughage, Double dmp, Double dmd, Double medm, Double cp, Double dg, Double ee, Double adip2cp, Double phos, Double sulf, Double ashAlk, Double maxPass) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Grazplan\Supplement.cs:line 241

   at Models.GrazPlan.SupplementModel..ctor() in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Grazplan\Supplement.cs:line 66

   at Models.GrazPlan.Supplement..ctor() in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Grazplan\Supplement.cs:line 826

   at CreateModels.GrazPlan.Supplement()

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)

   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)

   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)

   at Models.Core.ApsimFile.FileFormat.ReadFromString[T](String st, List`1& creationExceptions, String fileName) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Core\ApsimFile\FileFormat.cs:line 90

   at Models.Core.ApsimFile.FileFormat.ReadFromFile[T](String fileName, List`1& creationExceptions) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Core\ApsimFile\FileFormat.cs:line 66

   at Models.Core.Run.SimulationGroup.Initialise() in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Core\Run\SimulationGroup.cs:line 183

   --- End of inner exception stack trace ---

----------------------------------------------

System.Exception: Error in file:C:\Jenkins\workspace\PullRequest_v2\ApsimX\Tests\UnderReview\Stock\StockExample.apsimx ---> System.NullReferenceException: Object reference not set to an instance of an object.

   at Models.GrazPlan.FoodSupplement.ParseText(String suppSt, Boolean nameOnly) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Grazplan\GrazSupp.cs:line 773

   at Models.GrazPlan.FoodSupplement..ctor(String suppSt) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Grazplan\GrazSupp.cs:line 279

   at Models.GrazPlan.SupplementModel.AddToStore(Double suppKg, String suppName, Int32 roughage, Double dmp, Double dmd, Double medm, Double cp, Double dg, Double ee, Double adip2cp, Double phos, Double sulf, Double ashAlk, Double maxPass) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Grazplan\Supplement.cs:line 241

   at Models.GrazPlan.SupplementModel..ctor() in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Grazplan\Supplement.cs:line 66

   at Models.GrazPlan.Supplement..ctor() in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Grazplan\Supplement.cs:line 826

   at CreateModels.GrazPlan.Supplement()

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)

   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)

   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)

   at Models.Core.ApsimFile.FileFormat.ReadFromString[T](String st, List`1& creationExceptions, String fileName) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Core\ApsimFile\FileFormat.cs:line 90

   at Models.Core.ApsimFile.FileFormat.ReadFromFile[T](String fileName, List`1& creationExceptions) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Core\ApsimFile\FileFormat.cs:line 66

   at Models.Core.Run.SimulationGroup.Initialise() in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Core\Run\SimulationGroup.cs:line 183

   --- End of inner exception stack trace ---

ERRORS FOUND!!
```

**Comment by her123** [comment]
Do these properties and methods need to be static?

**Comment by zur003** [comment]
I don't think it's necessary for this to be static. If I recall, it was intended more as an optimisation, as new instances of FoodSupplement objects are created rather frequently, and it's inefficient to re-parse the default supplement information each time. It should be possible for this to safely be static if we add a suitable lock.
