### ISSUE TITLE
converter disappeared in the uI

### ISSUE THREAD

**Issue by junqi108** [APSIMInitiative/ApsimX#5646]
just would like to use the coverter to upgrade my model version today, and 
i found it is disappeared in the UI (:-
![image](https://user-images.githubusercontent.com/13222562/92664209-76db2880-f357-11ea-8a78-bb0f7ebc96ca.png)

**Comment by hol430** [comment]
You mean to upgrade the resource files? You can use "Upgrade Resource Files" (third option from the right)

**Comment by frank0434** [comment]
I think this is the bottom Junqi is after
![image](https://user-images.githubusercontent.com/30789416/92664448-21534b80-f358-11ea-8f64-b5f6c7866289.png)

**Comment by hol430** [comment]
Ah, ok - yeah that was removed in favour of the upgrade resource files button. You can mimic the old functionality by opening the file and hitting save. But why do you want to explicitly upgrade the file anyway? Normally you should be able to just ignore the file version.

**Comment by junqi108** [comment]
@hol430 thanks drew. the reason i asked about this is that I conducted a big parameter optimization based on the apsim version of 4.8.2020. the optimization has been completed and i would like to save it to the new version. As there were lots of changes that i made to the code, thus i would like to use the optimized old grapevine model version to replace the one in the git repository.
however, when run it with the new version, it pop out many errors. i thought the errors could be solved by the converter at least partly. i will try to look more specifically to solve each error. 

System.Exception: ERROR in file: C:\ApsimX\Prototypes\Grapevine\temp3.2502916_4.3105945_1.2040312_3.6880782_3.9759648_3.7267569_4.1096113_3.7571701_4.2149849_5.2539416_5.7566154.apsimx
Simulation name: RetainedNodeNumNode36
System.Exception: Cannot find a match for link root in model .RetainedNodeNumNode36.Alley.PlantVariables.Script
   at Models.Core.Links.ResolveInternal(Object obj, ScopingRules scope, Boolean throwOnFail) in C:\ApsimX\Models\Core\Links.cs:line 176
   at Models.Core.Links.Resolve(IModel rootNode, Boolean allLinks, Boolean recurse, Boolean throwOnFail) in C:\ApsimX\Models\Core\Links.cs:line 46
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\ApsimX\Models\Core\Simulation.cs:line 264 ---> System.Exception: Cannot find a match for link root in model .RetainedNodeNumNode36.Alley.PlantVariables.Script
   at Models.Core.Links.ResolveInternal(Object obj, ScopingRules scope, Boolean throwOnFail) in C:\ApsimX\Models\Core\Links.cs:line 176
   at Models.Core.Links.Resolve(IModel rootNode, Boolean allLinks, Boolean recurse, Boolean throwOnFail) in C:\ApsimX\Models\Core\Links.cs:line 46
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\ApsimX\Models\Core\Simulation.cs:line 264
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\ApsimX\Models\Core\Simulation.cs:line 284
   at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in C:\ApsimX\Models\Core\Run\SimulationDescription.cs:line 115
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in C:\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 179

**Comment by hol430** [comment]
Hi Junqi, yeah there was a converter a few versions ago which can sometimes break manager scripts. I think the PlantVariables scripts in some of the examples may have been affected and might require manual changes. If you haven't changed your PlantVariables script, then you could replace it with the version in one of the example files. Otherwise if you upload your .apsimx file I might be able to make some manual fixes.

**Comment by junqi108** [comment]
thanks Drew. I compared the old version and new version of my model, and copied the plant variable scripts from the repository, and it worked ^-^. i will submit a pull request later. cheers.
