### ISSUE TITLE
PostSimulationTools\SimulationStats.cs issues

### ISSUE THREAD

**Issue by MarkLieffering** [APSIMInitiative/ApsimX#5680]
In the code for \ApsimX\Models\PostSimulationTools\SimulationStats.cs which generates simulation statistics as in the screenshot below:

![image](https://user-images.githubusercontent.com/32279744/93832169-045c3800-fcc9-11ea-9dc7-d183303a6075.png)

 1. can the "om" please be changed to "on" - it triggers me every time!
2. the fields to split on can't have a space after the comma - throws this error - not a biggy but when typing lists it is intuitive to put a space after the comma:

System.Exception: Cannot find field  Zone in table 
   at Models.PostSimulationTools.SimulationStats.Run() in ....\ApsimX\Models\PostSimulationTools\SimulationStats.cs:line 90
   at Models.Core.Run.SimulationGroup.RunPostSimulationTools() in ...\ApsimX\Models\Core\Run\SimulationGroup.cs:line 303

Cheers

**Comment by MarkLieffering** [comment]
Just to note/add in the filter (\ApsimX\Models\PostSimulationTools\Filter.cs) the csv list allows spaces after the comma
