### ISSUE TITLE
In MapConcentration, the number of values doesn't match the number of thickness

### ISSUE THREAD

**Issue by Chloe0317** [APSIMInitiative/ApsimX#5796]
I'm trying to set up a simulation using WEIRDO that keeps running into the error
"In MapConcentraction, the number of values doesn't match the number of thicknesses." 

The "concentraction" is a typo in Models\Soils\Standardiser\Layers.cs line212

However, I've double and triple checked that each soil depth set-up is the same. So I don't understand why this is happening. 
A copy of my .apsimx file can be accessed via: https://github.com/Chloe0317/APSIMsims 
Could someone help me with this please?
Thank you very much.

Details of the error is as follows:

System.Exception: Error in file: APSIM\WA_UMU00041.apsimx Simulation: ExperimentRepellencyHigh ---> System.Exception: In MapConcentraction, the number of values doesn't match the number of thicknesses.
   at Models.Soils.Standardiser.Layers.MapConcentration(Double[] fromValues, Double[] fromThickness, Double[] toThickness, Double defaultValueForBelowProfile, Boolean allowMissingValues) in C:\ApsimX\ApsimX-master\Models\Soils\Standardiser\Layers.cs:line 213
   at Models.Soils.Standardiser.Layers.LL15Mapped(IPhysical physical, Double[] ToThickness) in C:\ApsimX\ApsimX-master\Models\Soils\Standardiser\Layers.cs:line 445
   at Models.Soils.Standardiser.Layers.MapSW(Double[] fromValues, Double[] fromThickness, Double[] toThickness, Soil soil) in C:\ApsimX\ApsimX-master\Models\Soils\Standardiser\Layers.cs:line 311
   at Models.Soils.Standardiser.Layers.SetSampleThickness(Sample sample, Double[] thickness, Soil soil) in C:\ApsimX\ApsimX-master\Models\Soils\Standardiser\Layers.cs:line 158
   at Models.Soils.Standardiser.Layers.Standardise(Soil soil) in C:\ApsimX\ApsimX-master\Models\Soils\Standardiser\Layers.cs:line 32
   at Models.Soils.Standardiser.SoilStandardiser.Standardise(Soil soil) in C:\ApsimX\ApsimX-master\Models\Soils\Standardiser\SoilStandardiser.cs:line 14
   at Models.Core.Run.SimulationDescription.ToSimulation() in C:\ApsimX\ApsimX-master\Models\Core\Run\SimulationDescription.cs:line 160
   --- End of inner exception stack trace ---
   at Models.Core.Run.SimulationDescription.ToSimulation() in C:\ApsimX\ApsimX-master\Models\Core\Run\SimulationDescription.cs:line 168
   at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in C:\ApsimX\ApsimX-master\Models\Core\Run\SimulationDescription.cs:line 114
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in C:\ApsimX\ApsimX-master\APSIM.Shared\JobRunning\JobRunner.cs:line 179

**Comment by hol430** [comment]
Looks like this is occurring because the depths/thicknesses in the weirdo node haven't been specified. In fact, due to a bug, there is no depth column showing up in the weirdo UI. This is fixed by #5797 - a new upgrade should be available after it gets merged.

**Comment by Chloe0317** [comment]
Thank you very much Drew! Really appreciate it!
The WEIRDO.apsimx file was running fine so I didn't realise that the weirdo UI should have a depth column.
