### ISSUE TITLE
Issue running SWIM for potato

### ISSUE THREAD

**Issue by cranju** [APSIMInitiative/ApsimX#5798]
Hi,

I am trying to run APSIM for potato but I am getting the following error:

System.Exception: ERROR in file: C:\Users\ranjuc\Desktop\APSIM\Potato dataset\ranju_trial.apsimx
Simulation name: W1
System.Exception: Swim failed to find solution
   at Models.Soils.Swim3.OnProcess()
   at Models.Clock.OnDoCommence(Object sender, CommenceArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) ---> System.Exception: Swim failed to find solution
   at Models.Soils.Swim3.OnProcess()
   at Models.Clock.OnDoCommence(Object sender, CommenceArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken)
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken)
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager)

Can somebody help me in understanding what the problem is ?

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - please note this question has yet to be answered

**Comment by HamishBrownPFR** [comment]
Swim is a Richards equation soil water balance that does not converge in some situations.  If you are not needing the more detailed soil water model I suggest using SoilWat instead which is a tipping bucket model but will always find a problem.   If Swim is needed... Try breaking the soil up into thinner layers or different initial water conditions.

**Comment by cranju** [comment]
Thanks Hamish...I will try doing that. Actually I need to use both SoilWat and SWIM.
