### ISSUE TITLE
Morris Sensitivity - R entry

### ISSUE THREAD

**Issue by env99** [APSIMInitiative/ApsimX#5879]
I'm trying to run the MorrisMethodExample (Urine Patch) but it's throwing an error: ''Unable to find R entry in Registry - is R installed?'' 

How do I find the registry it speaks of so I can find this R?

System.Exception: Error in file:C:\Users\s0531636\Documents\Apsim\Examples\sensmorristest2.apsimx ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Unable to find R entry in Registry - is R installed?.
   at Models.Utilities.R.GetRInstallDirectoryFromRegistry()
   at Models.Utilities.R.GetRExePath()
   at Models.Utilities.R..ctor(CancellationToken cancelToken)
   at Models.Morris.OnBeginRun(Object sender, EventArgs e)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Models.Core.Events.Publish(String eventName, Object[] args)
   at Models.Core.Run.SimulationGroup.Initialise()
   --- End of inner exception stack trace ---

**Comment by frank0434** [comment]
Have you installed the [R software](https://www.r-project.org/)? 
Seems to me that the apsimx could find the software. 

I am doing sensitivity analysis by using the morris mothed. 
In the apsim [documentation](https://apsimdev.apsim.info/ApsimX/Releases/2020.11.20.5818/Sensitivity_MorrisMethod.pdf),
it says the sampling method and posterior analysis are all processed in R via the package called `sensitivity`. Apsimx will take the sampled values and create the simulations.

**Comment by hol430** [comment]
Yep, you need to install R. You can download it from [here](https://cran.r-project.org/bin/windows/base/).

**Comment by env99** [comment]
Thank you for the help. I hadn't realized R was not within APSIM but was an external system I needed to download. The Morris Example is working now.
