### ISSUE TITLE
Cannot serialize delegates

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#5904]
I occasionally get this error upon performing a simulation and it's not fully repeatable.
Not sure if this is related to CLEM or not.
It goes away with a restart of APSIM

System.Exception: Error in file: C:\Data\Source\Repos\ApsimX\Examples\CLEM\CLEM_Example_Cropping.apsimx Simulation: Rotation cropping ---> System.Runtime.Serialization.SerializationException: Cannot serialize delegates over unmanaged function pointers, dynamic methods or methods outside the delegate creator's assembly.
   at System.MulticastDelegate.GetObjectData(SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at Models.Core.Apsim.Clone[T](T model) in C:\Data\Source\Repos\ApsimX\Models\Core\Apsim.cs:line 71
   at Models.Core.Run.SimulationDescription.ToSimulation() in C:\Data\Source\Repos\ApsimX\Models\Core\Run\SimulationDescription.cs:line 131
   --- End of inner exception stack trace ---
   at Models.Core.Run.SimulationDescription.ToSimulation() in C:\Data\Source\Repos\ApsimX\Models\Core\Run\SimulationDescription.cs:line 168
   at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in C:\Data\Source\Repos\ApsimX\Models\Core\Run\SimulationDescription.cs:line 114
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in C:\Data\Source\Repos\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 179

**Comment by hol430** [comment]
I think I've seen similar errors (maybe the same?) on windows when using visual studio, after using the edit and continue feature. Could that be what's happening here?

**Comment by lie112** [comment]
I was in Visual studio but hadn't found and used the edit and continue feature, so that's not the cause.
I figured I'd just report all errors like this in case the error log helped solve a problem.
