### ISSUE TITLE
Jenkins builds are occasionally failing on clem

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#6103]
@lie112 - this pull request has just changed the stock example but jenkins is reporting a failure in clem. If you look through the logs you'll find the below error. Without having looked at the clem code, I'm guessing this is occurring because jenkins runs multiple clem files in parallel and they attempt to write to the same file(?). We need this fixed today as this is holding up the stock sprint. I can implement a quick and dirty fix of pulling out the code where it's writing to this file but I'm guessing you'd like to implement something slightly more elegant...let me know what you think.

```
System.IO.IOException: The process cannot access the file 'C:\Jenkins\workspace\PullRequest_v2\ApsimX\Examples\CLEM\ActivitiesPerformedSummary.html' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at Models.CLEM.Reporting.ReportActivitiesPerformed.CreateHTMLVersion(DataTable data, String directoryPath, Boolean darkTheme) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\CLEM\Reporting\ReportActivitiesPerformed.cs:line 609
   at Models.CLEM.Reporting.ReportActivitiesPerformed.CreateDataTable(IDataStore dataStore, String directoryPath, Boolean darkTheme) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\CLEM\Reporting\ReportActivitiesPerformed.cs:line 442
   at Models.CLEM.Reporting.ReportActivitiesPerformed.OnCompleted(Object sender, EventArgs e) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\CLEM\Reporting\ReportActivitiesPerformed.cs:line 148
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Core\Simulation.cs:line 292
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in C:\Jenkins\workspace\PullRequest_v2\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 179
```

_Originally posted by @hol430 in https://github.com/APSIMInitiative/ApsimX/issues/6093#issuecomment-769437832_

**Comment by lie112** [comment]
I wonder why that file is kept open. It should just be an immediate write and close, unless there is some threading happening.
I was looking at adding a RunClean (or SimpleExecution or name to be agreed upon) option (or maybe having it as an an enum to provide more functionality from a single setting ExecutionStyle: NoUserInterface, PerformanceOptimised, NormalExecution) property in the master settings of APSIM Next Gen that anyone could use to decide whether to perform interface and user related actions. For example, when doing HPC runs (and for jenkins tests) I would turn this on (NoUserInterface or PerformanceOptimised) and not include any Summary Description generation or performing validation in CLEM thus speeding up the run for non UI users.

**Comment by hol430** [comment]
I expect the file handle actually is being closed correctly, and it's just multiple threads (or potentially processes) are reaching this point in execution at the same time. Another potential solution might be to write the data to the .db file or to the summary component in the simulation. Or add a unique identifier (or simulation name?) as a pre/suffix to the filename.

**Comment by lie112** [comment]
This file creation is not designed for multiple runs or runs without the need of UI and model feedback to the user.
Is it possible to add properties to the APSIM properties (e.g. dark mode etc) as stated above. I can't think where I would otherwise add a system wide CLEM property that controls what we need here. I basically need 4 or five levels of output from verbose (create all summary descriptions and html reports) to quite and efficient (do not even perform CLEM validation). 
Do you have a way of turning off documentation when performing Jenkins validation or HPC simulations? This would also suffice as there's a few html files from CLEM that do not need to be written outside single simulation runs by the user.

**Comment by hol430** [comment]
The properties like dark mode are gui-level and won't be accessible from models. Since the code to generate the html file is in models, you won't be able to check any of these properties. One option might be to make your model implement `IPostSimulationTool`. The post-simulation tools are run serially, so you won't have to worry about concurrent file access - I think you could safely generate the html file inside the `Run()` method defined by this interface.

**Comment by lie112** [comment]
Oh ok. That makes sense they are all UI properties.
Have we ever considered a similar config file for the model level or can we add properties to Model.Simulation and provide both the description and properties in the display? I'm happy to only add properties that could be useful to a range of models. These simulation level properties could also be used to help determine what summary details are reported #6112.
I'm happy to shift the offending writing of html to PostSimulation, but turning it off is also a valid option.

**Comment by hol430** [comment]
Thinking about this some more, I've realised that using a post-simulation tool won't actually solve the problem when running multiple .apsimx files in parallel. (It only helps when running multiple simulations in a single file.)

**Comment by lie112** [comment]
I already have the ability to turn this feature off. It is a setting in the ZoneCLEM Model. Turning this automatic generation off will solve the problem. It is only turned on so that users getting the example files will have it on for their runs and not have to change the value manually.

I still l think my idea of a property somewhere that dictates the level of reporting/output/additional calculations will solve the problem and assist me with the DARPA project and HPC runs where I may want to ignore all validation and all descriptive summary output optimised for speed and threading (also for jenkins). It could be a couple properties to separate this logic. PerformValidation (T/F), and xxx (can think of the name right now) but something to turn on descriptive reporting. Is documention performed on each "run"? This would also allow that overhead to be suppressed unless you already have that somewhere. Of course these are dangerous properties for beginners as they may have validation turned off when really needed.

My suggestion is for a property on Simulation model as it is the highest level as Simulations is just a folder from what I can see. 
This would require the display of the Simulation in the UI to provide both a PropertyPresenter and a MarkDownPresenter.
