### ISSUE TITLE
Autodoc threading issue

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#6178]
I'm regularly getting failures when trying to create documentation for PMF models. The failure is an IOException, with a complaint that the process cannot access the file CurveNumberCover.png because it is being used by another process.

**Comment by junqi108** [comment]
I got the same issue as well. eager to know how to solve it. 

System.IO.IOException: The process cannot access the file 'C:\Users\hrmjxz\AppData\Local\Temp\autodoc\CurveNumberCover.png' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at UserInterface.Classes.HtmlToMigraDoc.GetImagePath(String imageName, String imageDirectory) in C:\ApsimX\ApsimNG\Classes\HtmlToMigraDoc.cs:line 192
   at UserInterface.Classes.HtmlToMigraDoc.AddImage(HtmlNode node, DocumentObject section, String imagePath, String relativePath) in C:\ApsimX\ApsimNG\Classes\HtmlToMigraDoc.cs:line 175
   at UserInterface.Classes.HtmlToMigraDoc.ParseNode(HtmlNode node, DocumentObject section, String imagePath, String relativePath) in C:\ApsimX\ApsimNG\Classes\HtmlToMigraDoc.cs:line 133
   at UserInterface.Classes.HtmlToMigraDoc.ConvertNodes(HtmlNodeCollection nodes, DocumentObject section, String imagePath, String relativePath) in C:\ApsimX\ApsimNG\Classes\HtmlToMigraDoc.cs:line 64
   at UserInterface.Classes.HtmlToMigraDoc.ConvertNodes(HtmlNodeCollection nodes, DocumentObject section, String imagePath, String relativePath) in C:\ApsimX\ApsimNG\Classes\HtmlToMigraDoc.cs:line 66
   at UserInterface.Classes.HtmlToMigraDoc.Convert(String html, DocumentObject section, String imagePath, String relativePath) in C:\ApsimX\ApsimNG\Classes\HtmlToMigraDoc.cs:line 48
   at ApsimNG.Classes.PDFWriter.AddFormattedParagraphToSection(Section section, Paragraph paragraph) in C:\ApsimX\ApsimNG\Classes\PDFWriter.cs:line 530
   at ApsimNG.Classes.PDFWriter.TagsToMigraDoc(Section section, List`1 tags) in C:\ApsimX\ApsimNG\Classes\PDFWriter.cs:line 391
   at ApsimNG.Classes.PDFWriter.CreatePDF(List`1 tags, String fileName) in C:\ApsimX\ApsimNG\Classes\PDFWriter.cs:line 126
   at UserInterface.Commands.CreateFileDocumentationCommand.CreatePDF(String modelNameToExport) in C:\ApsimX\ApsimNG\Commands\CreateFileDocumentationCommand.cs:line 85
   at UserInterface.Commands.CreateFileDocumentationCommand.Do() in C:\ApsimX\ApsimNG\Commands\CreateFileDocumentationCommand.cs:line 45
   at UserInterface.Presenters.ContextMenu.CreateFileDocumentation(Object sender, EventArgs e) in C:\ApsimX\ApsimNG\Menus\ContextMenu.cs:line 898

**Comment by hol430** [comment]
Which file are you seeing this problem in? I'm struggling to reproduce the problem

**Comment by zur003** [comment]
I see it with the Wheat example simulation, although I'm running under the IDE.
