### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by her123** [APSIMInitiative/ApsimX#6357]
System.Exception: Error during Import: Exception has been thrown by the target of an invocation. Value cannot be null.
Parameter name: input
   at UserInterface.Presenters.MainPresenter.Import(String fileName) in C:\Users\her123\Projects\ApsimX\ApsimNG\Presenters\MainPresenter.cs:line 1119
   at UserInterface.Presenters.MainPresenter.OnImport(Object sender, EventArgs e) in C:\Users\her123\Projects\ApsimX\ApsimNG\Presenters\MainPresenter.cs:line 1092

[test_imports.zip](https://github.com/APSIMInitiative/ApsimX/files/6314567/test_imports.zip)

**Comment by her123** [comment]
The import of the Yeelanna 2014 fails to import the memo notes
