### ISSUE TITLE
%root% is not working for the met path

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#6405]
In the master branch of ApsimX, %root% is not working for the met path.

Under the `Examples` folder, open the Windows terminal, then run command 

```
..\Bin\Debug\net472\Models.exe Wheat.apsimx
```

Then I get this error

```
ERROR in file: C:\ApsimX\Examples\Wheat.apsimx
Simulation name: Simulation
Models.Core.SimulationException ---> Models.Core.ApsimXException: Cannot find weather file '%root%\Examples\WeatherFiles\Dalby.met'
   at Models.Climate.Weather.GetMetData(DateTime date)
   at Models.Climate.Weather.OnDoWeather(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Models.Clock.OnDoCommence(Object sender, CommenceArgs e)
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken)
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken)
   at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken)
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager)
ERRORS FOUND!!
```

I believe the same command is working before.

**Comment by hol430** [comment]
Hi @byzheng, I've done some testing to reproduce this with mixed results. Initially I was getting the same error on windows, but after doing a git clean to remove some old build files, the error disappeared. You will want to be careful with git clean though - as it can delete files which you might not want deleted. For a start can you delete the Bin directory (capital B) if it exists?

If the error still occurs, you could try `git clean -xfd`, but this will delete files which git would normally ignore (such as .db files), so be careful if you do this.

**Comment by byzheng** [comment]
Thanks @hol430  This problem is fixed now.
