### ISSUE TITLE
The Swim3 UI is throwing an error - "The view must be an IPropertyView instance" ...

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#6420]
... so there is no access to the parameters for Swim3. Not sure when this happened but I think it was fine about 22-25 March.

System.ArgumentException: The view must be an IPropertyView instance
   at UserInterface.Presenters.PropertyPresenter.Attach(Object model, Object view, ExplorerPresenter explorerPresenter) in C:\aaUnderVC\apsimNextGen\ApsimNG\Presenters\PropertyPresenter.cs:line 69
   at UserInterface.Presenters.ExplorerPresenter.ShowInRightHandPanel(Object model, ViewBase newView, IPresenter presenter) in C:\aaUnderVC\apsimNextGen\ApsimNG\Presenters\ExplorerPresenter.cs:line 816
   at UserInterface.Presenters.ExplorerPresenter.ShowInRightHandPanel(Object model, String viewName, String presenterName) in C:\aaUnderVC\apsimNextGen\ApsimNG\Presenters\ExplorerPresenter.cs:line 779
   at UserInterface.Presenters.ExplorerPresenter.ShowRightHandPanel() in C:\aaUnderVC\apsimNextGen\ApsimNG\Presenters\ExplorerPresenter.cs:line 762
   at UserInterface.Presenters.ExplorerPresenter.OnNodeSelected(Object sender, NodeSelectedArgs e) in C:\aaUnderVC\apsimNextGen\ApsimNG\Presenters\ExplorerPresenter.cs:line 914

**Comment by hol353** [comment]
I can't reproduce this one. I can see and edit the Swim3 parameters from the GUI. Are you using the latest version of APSIM? Can you attach your .apsimx file?
