### ISSUE TITLE
Scripts in the management tool box needs some update

### ISSUE THREAD

**Issue by junqi108** [APSIMInitiative/ApsimX#6425]
I was using the Reset on date script from the management toolbox. 

However, it seems the nutrient link seems can not be found in the grapevine model. 

Furthermore, the fertilizer topup script is also not working as well.  The Solute NO3 link is missing. 
is it possible to add the management script example into several simple plant models and let Jenkins auto test them as well. 

System.Exception: Cannot find a match for link nutrient in model .RetainedNodeNumNode72.Row.Reset on date.Script
   at Models.Core.Links.ResolveInternal(Object obj, ScopingRules scope, Boolean throwOnFail)
   at Models.Core.Links.Resolve(IModel rootNode, Boolean allLinks, Boolean recurse, Boolean throwOnFail)
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) ---> System.Exception: Cannot find a match for link nutrient in model .RetainedNodeNumNode72.Row.Reset on date.Script
   at Models.Core.Links.ResolveInternal(Object obj, ScopingRules scope, Boolean throwOnFail)
   at Models.Core.Links.Resolve(IModel rootNode, Boolean allLinks, Boolean recurse, Boolean throwOnFail)
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken)
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken)
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager)

using Models.Soils.Nutrients;
using APSIM.Shared.Utilities;
using Models.Surface;
using Models.Utilities;
using Models.Soils.Nutrients;
using Models.Soils;
using Models.PMF;
using Models.Core;
using System;
using Models.Interfaces;

namespace Models
{
    [Serializable]
    public class Script : Model
    {
        [Link] private Clock Clock;
        [Link] private Plant Wheat;
        [Link] private ISoilWater SoilWater;
        [Link] private Nutrient nutrient;
        [Link] private SurfaceOrganicMatter SOM;
        [Link] private Summary Summary;

        [Description("Date to reset on:")]
        public string ResetDate {get;set;}

        [Description("Reset Water? (Yes or No)")]
        public string ResetWater {get;set;}

        [Description("Reset Soil Nutrients ? (Yes or No)")]
        public string ResetNutrients {get;set;}

        [Description("Reset Surface Organic Matter? (Yes or No)")]
        public string ResetSOM {get;set;}

        [EventSubscribe("DoManagement")]
        private void OnDoManagement(object sender, EventArgs e)
        {
            if (DateUtilities.WithinDates(ResetDate, Clock.Today, ResetDate))
            {
                if (ResetWater == "Yes")
                {
                    Summary.WriteMessage(this, "Reset Water");
                    SoilWater.Reset();
                }
                if (ResetNutrients == "Yes")
                {
                    Summary.WriteMessage(this, "Reset Nitrogen");
                    nutrient.Reset();
                }
                if (ResetSOM == "Yes")
                {
                    Summary.WriteMessage(this, "Reset Surface OM");
                    SOM.Reset();
                }
            }
        }
    }
}

**Comment by hol430** [comment]
Sounds like you have soilN in your soils, whereas this manager script expects nutrient. As far as I know, soilN is on the way out, so I'd recommend removing it from your simulations and adding nutrient instead. For the same reason, I think we want the scripts in the toolbox to use nutrient rather than soilN.

I think the problem with the fertiliser topup script is the same one, and it is expecting to see nutrient.

**Comment by junqi108** [comment]
thanks Drew. sorry for my ignorance on the soil nutrient part.

**Comment by hol430** [comment]
No worries - did you end up getting this working?
