### ISSUE TITLE
User Interface throws when running simulations

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#646]
I'm getting the error below run I run simulations from the GUI. Seems to be coming from RunCommand when the Timer ticks. I notice the timer class changed recently by @zur003. Related? Does the new timer tick on a different thread to the user interface thread.

System.InvalidOperationException occurred
  HResult=-2146233079
  Message=Cross-thread operation not valid: Control 'panel1' accessed from a thread other than the thread it was created on.
  Source=System.Windows.Forms
  StackTrace:
       at System.Windows.Forms.Control.get_Handle()
       at System.Windows.Forms.Control.get_InternalHandle()
       at System.Windows.Forms.Control.get_CreateParams()
       at System.Windows.Forms.TextBoxBase.get_CreateParams()
       at System.Windows.Forms.TextBox.get_CreateParams()
       at System.Windows.Forms.Control.CreateHandle()
       at System.Windows.Forms.TextBoxBase.CreateHandle()
       at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
       at System.Windows.Forms.Control.CreateControl()
       at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
       at System.Windows.Forms.Control.set_Visible(Boolean value)
       at UserInterface.Views.ExplorerView.ShowMessage(String message, ErrorLevel errorLevel) in D:\ApsimX\UserInterface\Views\ExplorerView.cs:line 337
  InnerException:

**Comment by zur003** [comment]
Yes, that will be the culprit. I was trying to move from System.Windows.Forms.Timer to System.Timers.Timer (to remove dependencies on System.Windows.Forms. The timers are similar in some respects, but System.Timers.Timer is indeed threaded separately. I thought using an invoker would get round the problem - it seemed to work for me.

**Comment by hol353** [comment]
Actually, I have caused this problem. I now see that you've put an invoker into ShowProgress. I need something similar in ShowMessage.
