### ISSUE TITLE
Batch-edit soil profiles using SLGA via R

### ISSUE THREAD

**Issue by Chloe0317** [APSIMInitiative/ApsimX#6773]
Not sure if this is the right place to ask this question but I'm looking to batch-edit soil profiles based on their locations using R, similar to @hol353 's suggestions in https://github.com/APSIMInitiative/ApsimX/issues/3655
I'm using the APSOIL database and ASRIS, first converting the xml soil file to json, however, the automatic replacement of soil node appears to be quite challenging particularly for one file with multiple simulations. 
Just wondering if anyone knows an existing function that does this or could give me some pointers please? @femiguez  @hol430 
Thanks!

> Another use case after a discussion with @rcichota:
> 
> I think we should support multiple soil databases (e.g. Apsoil, Soil and Landscape Grid Australia, ASRIS, ISRIC and LandCare NZ). We could add the ability for the user to simply supply a URL or some way of pointing to the soil without actually copying the soil into the simulation. At runtime APSIM could download the soil, add in missing parameters (e.g. SWCON) and use it on the fly. That way if you’re using an external tool (e.g. R / Python) you don’t need to do any infilling of missing parameters or conversion of XML/JSON formats. The user could just put the URL into the .apsimx file and it works.

**Comment by hol430** [comment]
One option is to invoke Models.exe with the --edit command-line option. There are details on [this page](https://apsimnextgeneration.netlify.app/usage/editfile/), including an example of changing some soil profile properties. You can call Models.exe from R with the `system()` function.

**Comment by femiguez** [comment]
In the apsimx R package (https://cran.r-project.org/package=apsimx) there are a couple of useful functions. One is the 'aspimx_soil_profile' which allows you to build an R object of class 'soil_profile'. There is another function (with a long name) 'edit_apsimx_replace_soil_profile' which can take that soil_profile object and replace the whole profile in the apsim simulation. It is possible that it might not handle your use case, so we can test it for your specific use and change it as needed. I only have functions to 'get' soil profiles from SSURGO or ISRIC, but I could look into getting data from the other databases used in Australia and New Zealand. I'm always happy to help. :)

**Comment by Chloe0317** [comment]
Dear @hol430  and @femiguez , 

Thank you both very much! What I've done temporarily is to write a wrapper function that allows converting data extracted from ASRIS to the *soil_profile* class in apsimx package then use the *edit_apsimx_replace_soil_profile* function to replace the soil. This works well with single simulation but not *.apsimx* file with multiple simulations. 
I do think it will be beneficial for the `apsimx` package to include methods of getting data from databases used in Australia and NZ though considering the user bases.

**Comment by femiguez** [comment]
@Chloe0317 you are correct I had not added this feature. The version of the package in github has a new argument 'root' in the 'edit_apsimx_replace_soil_profile' which allows you to edit specific simulations in an apsimx file. You can either test it yourself and let me know how it goes or send me a file that I can use for testing and I'll make sure that it works as intended. I will add as a feature request connecting to the different weather and soil databases specific to Australia and New Zealand - this will take some time. Notice that some of them have global coverage. For soils I have ISRIC. For weather there is nasapower (in github I also added chirps) and GSOD.

**Comment by Chloe0317** [comment]
Hi @femiguez, thanks for editing the function, unfortunately it seems I have too many nested simulations for the root arguement to work, as shown in the figure below. 
![1631256596(1)](https://user-images.githubusercontent.com/63323287/132812089-6e901e71-b0da-43b8-aacb-cf5d8c96b30c.png)
So I've proceeded to use the command line replacement, by writing soils into a tmp .apsimx file then replacing it to relevant path in my main simulations. The command line edit works well with properties but I couldn't get replacing entire soil model to work I have received the following errors. Both sims work and show the soil as 'Models.Soils.Soil' so I really don't know where it went wrong.  Kindly help please @hol430 

Also, when I edited the properties through command line, the changes listed in the config file were applied to the .apsimx file, the .apsimx was run, but the changes to property were not written to the file. Could I just edit the property and save the edit without running the simulations please?

I've used powershell here just to escape the white spaces in my folder, since OneDrive insists folder naming with white spaces and I'm not at liberty to change it.

Thanks heaps!
```
writeLines(".Simulations.Simulation.Field.Soil = oneSoil.apsimx;.Simulations.Simulation.Field.Soil", "tmp/mytmp.conf")
ada <- '~/GitHub/APSIMInitiativeX/bin/Debug/net472/Models.exe'
fedit <- '~/Modelling/SoilN/tmp/wheat.apsimx'
conf <- '~/Modelling/SoilN/tmp/mytmp.conf'
run.strng <- paste0("powershell -command ", ada, " ", fedit," --edit ", conf)
system(run.strng)
```
The command line edit works with properties but I couldn't get replacing entire soil model to work I have received the following errors. Both sims work and show the soil as 'Models.Soils.Soil' so I really don't know where it went wrong.  Kindly help please @hol430 
[sims.zip](https://github.com/APSIMInitiative/ApsimX/files/7141843/sims.zip)


```
System.FormatException: Unable to convert oneSoil.apsimx;.Simulations.Simulation.Field.Soil to type Models.Soils.Soil ---> System.InvalidCastException: Invalid cast from 'System.String' to 'Models.Soils.Soil'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at APSIM.Shared.Utilities.ReflectionUtilities.StringToObject(Type dataType, String newValue, IFormatProvider format)
   --- End of inner exception stack trace ---
   at APSIM.Shared.Utilities.ReflectionUtilities.StringToObject(Type dataType, String newValue, IFormatProvider format)
   at APSIM.Shared.Utilities.ReflectionUtilities.StringToObject(Type dataType, String newValue)
   at Models.Core.ApsimFile.EditFile.ChangeVariableValue(IVariable variable, String value)
   at Models.Core.ApsimFile.EditFile.ApplyChanges(Simulations file, IEnumerable`1 factors)
   at Models.Core.ApsimFile.EditFile.Do(String apsimxFilePath, String configFilePath)
   at Models.Program.<>c__DisplayClass5_0.<Run>b__2(String f)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at Models.Core.Run.Runner..ctor(IEnumerable`1 relativeTo, Boolean runSimulations, Boolean runPostSimulationTools, Boolean runTests, IEnumerable`1 simulationNamesToRun, RunTypeEnum runType, Boolean wait, Int32 numberOfProcessors, String simulationNamePatternMatch)
   at Models.Program.Run(Options options)```

**Comment by femiguez** [comment]
@Chloe0317 I made some minor improvements to the function to handle your application. I have not tested it. The root argument for your simulation might need to be root = c("InCrop", "Paddock1", "1_Schwenke") for the first one and then you would need to change it for the second one and so on. In R you could write a loop to do this.

**Comment by hol430** [comment]
@Chloe0317 I tried your example and it worked for me. I didn't use R - I just manually ran the command from my shell, in the same directory as the .apsimx files - which may have made a difference, since you're using a relative path to oneSoil.apsimx in the config file. You could try specifying an absolute path to the .apsimx file and see if that makes a difference.

Yes, as you've discovered, the edit file feature no longer saves the changes to the .apsimx file on disk. We changed this to speed up parameter optimisations where we usually edit the file and then immediately run it. This is probably why Fernando found it slower than just changing the .json already loaded into memory. I'll look into adding in the option to edit the file without running.

**Comment by Chloe0317** [comment]
@hol430

**Comment by Chloe0317** [comment]
I accidentall

**Comment by Chloe0317** [comment]
@femiguez Dear Fernando, thanks for the edit, unfortunately it didn't work and returned the following error
`no root node label in position 2 found or root is not unique`

@hol430 Dear Drew, I just realized that the replacement actually worked despite returning the exact same error
`Unable to convert oneSoil.apsimx;.Simulations.Simulation.Field.Soil to type Models.Soils.Soil ---> System.InvalidCastException: Invalid cast from 'System.String' to 'Models.Soils.Soil'.`

Just like edit function, the soil was changed and the simulation was ran, without saving the changes to the .apsimx file, unfortunately I let the error message throw me off.
If there could be an implementation of editing and replacing without running and saving the changes to the apsimx file, it will be much appreciated please. Thanks!

**Comment by femiguez** [comment]
@Chloe0317 Sorry! Try instead root = c("InCrop", "Paddock1$", "1_Schwenke"). The error message means that it is finding more than one instance of "Paddock1", because you have also "Paddock13" and "Paddock15". The dollar sign at the end will hopefully make the expression unique.
@hol430 Thanks for the insight! I would suggest that the desired behavior would be to have '--edit' only edit the file and another option '--edit-run' (or similar) that would edit and run.

**Comment by Chloe0317** [comment]
@femiguez I noticed that for it to work for my simulation, [line 99](https://github.com/femiguez/apsimx/blob/86d064e86ff6fa84ce84a41706db5f9f20ae9770/R/edit_apsimx_replace_soil_profile.R#L99) of the R code `root.node.1.child.names <- sapply(root.node.1$Children, function(x) x$Name)` needs to be changed to `root.node.1.child.names <- sapply(root.node.1, function(x) x$Name)`
Thanks!

**Comment by femiguez** [comment]
@Chloe0317 Thanks for testing and for the suggestion! I'll write some tests to make sure the feature works as intended.
