### ISSUE TITLE
Report throws error and will not display data

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6812]
I have a  APISM report in a users simulation that throws an error and cannot be viewed in the UI

throws Object ref not set error
The table has values when inspected in DB Browser and I can't work out why the below error would be thrown

_System.NullReferenceException: Object reference not set to an instance of an object.
   at APSIM.Shared.Utilities.DataTableUtilities.GetColumnAsIntegers(DataTable table, String columnName) in C:\Data\Source\Repos\ApsimX\APSIM.Shared\Utilities\DataTableUtilities.cs:line 222
   at UserInterface.Views.PagedDataProvider.GetRollingCursorRowFilter(Int32 from, Int32 count) in C:\Data\Source\Repos\ApsimX\ApsimNG\Views\Sheet\PagedDataProvider.cs:line 181
   at UserInterface.Views.PagedDataProvider.GetData(Int32 startRowIndex) in C:\Data\Source\Repos\ApsimX\ApsimNG\Views\Sheet\PagedDataProvider.cs:line 139
   at UserInterface.Views.PagedDataProvider..ctor(IStorageReader store, String checkpointNameInScope, String dataTableName, IEnumerable`1 simulationNamesInScope, String columnNameFilter, String dataFilter, Int32 dataPageSize) in C:\Data\Source\Repos\ApsimX\ApsimNG\Views\Sheet\PagedDataProvider.cs:line 69
   at UserInterface.Presenters.DataStorePresenter.PopulateGrid() in C:\Data\Source\Repos\ApsimX\ApsimNG\Presenters\DataStorePresenter.cs:line 174_

It seems that the GetRollingCursorRow() method of PagedDataProvider returns null for "data" table from 
` var data = dataStore.GetDataUsingSql($"SELECT rowid FROM keyset WHERE rowid >= {from+1} ORDER BY rowid LIMIT {count}");`
And then throws the error when attempting to GetColumnAsInteger(data, "rowid")

I can't figure out what/where keyset is and how this is used.
Any idea why this fails for just this report in this simulation.
There are problems with the model and the data supplied but not producing errors, but I cant see this interfering with the report or display of data.
I can send @hol430  a zip file of apsimx, db and required input files to reproduce the problem.

The report has all the CheckPointID, SimulationID, Foldername and Zone columns
I have copied all variables from another sim where this works and I can see data generated (even after empty datasource and a delete of datasource)

Where did we get with the ability to display tables that do not to comply with this column naming?
We have added some dummy columns to avoid no data being displayed in some custom reports.

**Comment by hol430** [comment]
Hi @lie112 - if you still have the faulty file at hand could you upload it to this issue?

**Comment by lie112** [comment]
I eventually found the problem. The report name had a space in it.
We do allow spaces in component names, but what about Report names? Maybe the space was causing an issue in trying to locate or interrogate the data table. I assume this is a bug. We should be able to trap and stop this rather than hit the critical error while stepping through columns

**Comment by hol430** [comment]
Yep spaces in report names should work - I just gave this a shot and I get the same error as you. I've fixed the problem in this particular case, but there may be other models which build sql queries manually which may have similar problems if they don't quote the table name.
