### ISSUE TITLE
Sensitivity examples on Mac?

### ISSUE THREAD

**Issue by femiguez** [APSIMInitiative/ApsimX#6889]
The Morris and Sobol examples seem to run without issues on Windows, but on Mac there seems to be a problem. 
I open APSIM (I tired this with a couple of different versions 2021.8.12.6707 and 2021.10.11.6842) and then 'Open and Example'. I select either Morris or Sobol, then 'save as' and then try to run it. I get the error 

System.Exception: Error in file:/Users/fernandomiguez/Dropbox/csm/labs/10_lab/SobolLab.apsimx
 ---> System.Exception: Failed to publish event BeginRun. Error from subscriber BeginRun.OnBeginRun
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: StandardOut has not been redirected or the process hasn't started yet.
   at System.Diagnostics.Process.BeginOutputReadLine()
   at APSIM.Shared.Utilities.ProcessUtilities.ProcessWithRedirectedOutput.Start(String executable, String arguments, String workingDirectory, Boolean redirectOutput, CancellationToken cancelToken, Boolean writeToConsole, Dictionary`2 environment) in /tmp/ApsimX/APSIM.Shared/Utilities/ProcessUtilities.cs:line 266
   at Models.Utilities.R.GetPathToPackage(String package) in /tmp/ApsimX/Models/Utilities/R.cs:line 543
   at Models.Utilities.R.GetRExePath() in /tmp/ApsimX/Models/Utilities/R.cs:line 350
   at Models.Utilities.R..ctor(CancellationToken cancelToken) in /tmp/ApsimX/Models/Utilities/R.cs:line 73
   at Models.Sobol.OnBeginRun(Object sender, EventArgs e) in /tmp/ApsimX/Models/Sensitivity/Sobol.cs:line 201
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Models.Core.Events.Publish(String eventName, Object[] args) in /tmp/ApsimX/Models/Core/Events.cs:line 127
   --- End of inner exception stack trace ---
   at Models.Core.Events.Publish(String eventName, Object[] args) in /tmp/ApsimX/Models/Core/Events.cs:line 131
   at Models.Core.Run.SimulationGroup.Initialise() in /tmp/ApsimX/Models/Core/Run/SimulationGroup.cs:line 222
   --- End of inner exception stack trace ---

I don't think this is a new issue. I have never been able to run the Sensitivity examples on Mac.  @hut104 ?

**Comment by peter-devoil** [comment]
While not definitave and possibly unrelated, I observed multiple GUI crashes running in a mac's dropbox folder today, which seemed to cease when the file was saved locally.

**Comment by peter-devoil** [comment]
Yes, it was a released build. And yes, 7020 has been giving us grief.
