### ISSUE TITLE
Errors in UI getting buried by exception trace

### ISSUE THREAD

**Issue by fai04d** [APSIMInitiative/ApsimX#707]
The following error occurred when trying to copy a SoilCrop to another Water node:

Exception has been thrown by the target of an invocation.
                         at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
                         at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
                         at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
                         at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
                         at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
                         at Models.Core.VariableProperty.get_Value() in D:\ApsimX\Models\Core\VariableProperty.cs:line 231
                         at Models.Core.VariableProperty.get_Total() in D:\ApsimX\Models\Core\VariableProperty.cs:line 374
                         at UserInterface.Presenters.ProfilePresenter.CreateTable() in D:\ApsimX\UserInterface\Presenters\ProfilePresenter.cs:line 328
                         at UserInterface.Presenters.ProfilePresenter.PopulateGrid() in D:\ApsimX\UserInterface\Presenters\ProfilePresenter.cs:line 168
                         at UserInterface.Presenters.ProfilePresenter.Attach(Object model, Object view, ExplorerPresenter explorerPresenter) in D:\ApsimX\UserInterface\Presenters\ProfilePresenter.cs:line 109
                         at UserInterface.Presenters.ExplorerPresenter.ShowInRightHandPanel(Object model, String viewName, String presenterName) in D:\ApsimX\UserInterface\Presenters\ExplorerPresenter.cs:line 890

The actual error that comes from the debugger is:

Number of soil layers in SoilWater is different to number of layers in SoilWater.Crop

The problem was in fact the user trying to copy between two soils with different layer numbers.
The UI did not pick up that error and only displayed this stack trace to the user which didn't even include the reason for the error. The user was given no response that would help them determine the fault, even though it existed in the code.

We need to remove stack traces from the UI output. Users aren't going to know what this means and to be honest it's not that helpful for a developer either. The UI should only show the error reported by the module.

**Comment by hol353** [comment]
As part of this we need to make the Tests significant differences found not an error but more a warning.

**Comment by zur003** [comment]
Just a suggestion, but perhaps we could do the exception handling in such a way that the stack trace is provided if and only if the application is being run from the IDE. "Normal" users then wouldn't see all the details, but developers would. The main problem then would be ensuring we give "normal" users enough information to work out where things went wrong (in those cases where it's their problem, and not a developer's issue).

**Comment by hol430** [comment]
With regards to giving users enough information for us to help, would it be useful to write the full error (with stack trace and a timestamp) to some sort of log/error file, but within APSIM only display the actual message? Then, when they seek help, they can provide the log file.

And of course if it's being run from an IDE, just display the whole thing with stack trace in the APSIM status bar.

The problem, I guess, is that we'll no longer be debugging the code in the 'release' version.

**Comment by hol353** [comment]
I don't think we need a log file. All error messages with stack trace are written to the .db file in the Messages table. 

A few users have suggested that they don't want the full stack trace immediately visible (it obscures the error message) but have it available via a button or link in the message window at the bottom of the GUI.
