### ISSUE TITLE
Mac UI bugs

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/ApsimX#7247]
1. Open Examples/Rotation 
Navigate to Simulations/Mar/Mar/RotationManager
Move a node
Click off the component => error: "Non static method requires a target", 
   Bottom half of rotation UI is left behind,
   Can't close simulation tab.

```
System.Reflection.TargetException: Non-static method requires a target.
   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Utility.GtkUtil.DetachHandlers(Widget widget) in /tmp/ApsimX/ApsimNG/Utility/GtkUtilities.cs:line 37
   at Utility.GtkUtil.DetachAllHandlers(Widget widget) in /tmp/ApsimX/ApsimNG/Utility/GtkUtilities.cs:line 17
...
   at UserInterface.Views.ViewBase.Dispose(Boolean disposing) in /tmp/ApsimX/ApsimNG/Views/ViewBase.cs:line 247
   at UserInterface.Views.ViewBase.Dispose() in /tmp/ApsimX/ApsimNG/Views/ViewBase.cs:line 223
   at UserInterface.Views.ExplorerView.AddRightHandView(Object control) in /tmp/ApsimX/ApsimNG/Views/ExplorerView.cs:line 62
   at UserInterface.Presenters.ExplorerPresenter.HideRightHandPanel() in /tmp/ApsimX/ApsimNG/Presenters/ExplorerPresenter.cs:line 727
   at UserInterface.Presenters.ExplorerPresenter.OnNodeSelected(Object sender, NodeSelectedArgs e) in /tmp/ApsimX/ApsimNG/Presenters/ExplorerPresenter.cs:line 912
```

2. Open Examples/Oats
   Navigate ...Field/SowingRule1
   Change the sowing date to something "illegal"
   Click cultivar twice => crash
```
(ApsimNG:808): Gtk-CRITICAL **: 20:41:23.218: gtk_menu_set_active: assertion 'GTK_IS_MENU (menu)' failed
(ApsimNG:808): Gtk-CRITICAL **: 20:41:23.219: gtk_widget_set_size_request: assertion 'GTK_IS_WIDGET (widget)' failed
(ApsimNG:808): Gtk-CRITICAL **: 20:41:23.219: gtk_widget_get_preferred_width: assertion 'GTK_IS_WIDGET (widget)' failed
(ApsimNG:808): Gtk-CRITICAL **: 20:41:23.219: gtk_widget_set_size_request: assertion 'GTK_IS_WIDGET (widget)' failed
(ApsimNG:808): GLib-GObject-WARNING **: 20:41:23.219: invalid (NULL) pointer instance
(ApsimNG:808): GLib-GObject-CRITICAL **: 20:41:23.219: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
(ApsimNG:808): GLib-GObject-CRITICAL **: 20:41:23.219: g_object_set: assertion 'G_IS_OBJECT (object)' failed
(ApsimNG:808): GLib-GObject-CRITICAL **: 20:41:23.219: g_object_set: assertion 'G_IS_OBJECT (object)' failed
(ApsimNG:808): Gtk-CRITICAL **: 20:41:23.219: gtk_menu_popup_at_widget: assertion 'GTK_IS_MENU (menu)' failed
(ApsimNG:808): Gtk-CRITICAL **: 20:41:23.219: gtk_menu_get_active: assertion 'GTK_IS_MENU (menu)' failed
zsh: segmentation fault  /Applications/APSIM2022.4.7025.0.app/Contents/MacOS/ApsimNG
```

**Comment by zur003** [comment]
Just for the record - problem 1 with RotationManager also occurs under the Windows version. Problem 2 does not (at least when tested under version 2022.4.7025).

**Comment by hol430** [comment]
I'm seeing problem 2 on linux. It doesn't always cause a crash for me, but I do get the warning messages from gtk.

**Comment by peter-devoil** [comment]
3. Open Barley example
   Navigate to the graph component in the field
   It can be duplicated by dragging it to the containing node (simulation)
   It can't be copied to the simulation or field nodes -  the "add" cursor changes, but nothing happens
   It can be "Add Model"ed 

Seems OK on linux though

**Comment by hol430** [comment]
I can't seem to reproduce that on mac or Linux. How are you trying to copy the graph? ctrl-c, ctrl-v? Right-click -> copy/paste? If you're trying to use command-c/command-v, that won't work - the keyboard shortcuts currently only work with ctrl key.

**Comment by peter-devoil** [comment]
Click, drag and drop.
The cursor changes over a dropsite  (has a + in it)
Letting go does nothing

Yes, using a mac without control bindings is a pain, the desktop's key accelerators aren't passed through to the VM..

**Comment by hol430** [comment]
Ahh, ok I see that now. Seems to be due to an inconsistency between the quartz and x11 backends for gdk. There's a simple fix, but it may result in slightly different dragging behaviour for mac vs Linux (and, presumably, windows). Normally, holding the shift key while dragging will cause a move operation, and dragging without holding shift will cause a copy. Under the quartz backend (ie on macos), it seems that the default operation is move, even while not holding shift.

**Comment by peter-devoil** [comment]
Ah. Native behaviour is best, so not a bug?

**Comment by hol430** [comment]
Native behaviour is certainly easier from my end :). If you think that's a reasonable default then I'll just commit my fix. It will probably only be a surprise people who regularly run the gui on different platforms.
