### ISSUE TITLE
Mac authorisation problems

### ISSUE THREAD

**Issue by jal-frezie** [APSIMInitiative/ApsimX#7253]
Trying to use Version 7021 on a Mac mini M1 I am getting permission problems. When I open my model I get:

APSIM.Shared.Utilities.SQLiteException: authorization denied
   at APSIM.Shared.Utilities.SQLite.OpenDatabase(String path, Boolean readOnly) in /tmp/ApsimX/APSIM.Shared/Utilities/SQLite.cs:line 424
   at Models.Storage.DataStore.Open() in /tmp/ApsimX/Models/Storage/DataStore.cs:line 247
   at Models.Storage.DataStore.OnCreated() in /tmp/ApsimX/Models/Storage/DataStore.cs:line 207
   at Models.Storage.DataStore.set_Parent(IModel value) in /tmp/ApsimX/Models/Storage/DataStore.cs:line 107
   at Models.Core.Model.ParentAllDescendants() in /tmp/ApsimX/Models/Core/Model.cs:line 519
   at Models.Core.ApsimFile.FileFormat.ReadFromString[T](String st, Action`1 errorHandler, Boolean initInBackground, String fileName) in /tmp/ApsimX/Models/Core/ApsimFile/FileFormat.cs:line 109

...but the model then seems to open OK. 

When I try to run it I get:

System.UnauthorizedAccessException: Access to the path '/Users/jaspert/Documents/My Simile files/Projects/ICRAF/HalfPollardedOnly.apsimx.bak' is denied.
 ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Models.Core.Simulations.Write(String FileName) in /tmp/ApsimX/Models/Core/Simulations.cs:line 169
   at UserInterface.Presenters.ExplorerPresenter.WriteSimulation(String fileName) in /tmp/ApsimX/ApsimNG/Presenters/ExplorerPresenter.cs:line 365
   at UserInterface.Presenters.ExplorerPresenter.Save() in /tmp/ApsimX/ApsimNG/Presenters/ExplorerPresenter.cs:line 321
   at UserInterface.Presenters.ContextMenu.RunAPSIM(Object sender, EventArgs e) in /tmp/ApsimX/ApsimNG/Menus/ContextMenu.cs:line 174

I deleted the old file at this location, and I have made sure to delete all the extended attributes from the directories in the path, but I still cannot run my model because of this problem. APSIM itself has the 'quarantine' xattr, but I have an earlier version installed which also has this and it does not seem to stop it working.

**Comment by jal-frezie** [comment]
Also got this one:
System.Exception: Cannot find a script compiler in manager.
   at Models.Manager.Compiler() in /tmp/ApsimX/Models/Management/Manager.cs:line 50
   at Models.Manager.RebuildScriptModel() in /tmp/ApsimX/Models/Management/Manager.cs:line 145
   at Models.Manager.set_Code(String value) in /tmp/ApsimX/Models/Management/Manager.cs:line 81
   at UserInterface.Presenters.ManagerPresenter.BuildScript() in /tmp/ApsimX/ApsimNG/Presenters/ManagerPresenter.cs:line 179

I suspect there's something wrong with my installation.

**Comment by jal-frezie** [comment]
All works well when I run it as superuser !!

**Comment by jal-frezie** [comment]
Actually, all works well when I run it from the command line even as regular user. And indeed it is not the only app where I have seen this sort of problem since "up"grading to Monterey.

**Comment by peter-devoil** [comment]
I observed similar messages after copying a simulation from a dropbox folder to a local Documents folder. Have been told of similar permissiony issues when running from a windows VM.

**Comment by hol430** [comment]
Does this still occur if you give full disk access to apsim in settings -> security & privacy -> privacy -> full disk access?

**Comment by jal-frezie** [comment]
Just tried it -- yes it does.
