### ISSUE TITLE
Batch import apsim file into apsimx

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#7470]
I try the `Import old .apsim file` for the main menu, and it is working for my apsim files. Is there a way to batch import files from command line as I have a few hundreds of apsim files.

**Comment by byzheng** [comment]
I get an error message when I use `Models.exe path-file.apsim /Upgrade`.

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Models.Core.ApsimFile.ConverterUtilities.SearchReplaceManagerCode(XmlNode manager, String searchFor, String replaceWith) in C:\Canola\ApsimX\Models\Core\ApsimFile\ConverterUtilities.cs:line 199
   at Models.Core.ApsimFile.XmlConverters.UpgradeToVersion38(XmlNode node, String fileName) in C:\Canola\ApsimX\Models\Core\ApsimFile\XmlConverters.cs:line 1207
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Models.Core.ApsimFile.XmlConverters.DoConvert(String& st, Int32 toVersion, String fileName) in C:\Canola\ApsimX\Models\Core\ApsimFile\XmlConverters.cs:line 69
   at Models.Core.ApsimFile.Converter.DoConvert(String st, Int32 toVersion, String fileName) in C:\Canola\ApsimX\Models\Core\ApsimFile\Converter.cs:line 36
   at Models.Program.UpgradeFile(String file) in C:\Canola\ApsimX\Models\Main.cs:line 171
   at Models.Program.Run(Options options) in C:\Canola\ApsimX\Models\Main.cs:line 73
```

**Comment by byzheng** [comment]
Finally, I find another program `apsim.exe` to import old apsim files.

```
apsim.exe import path-to-file.apsim
```
