### ISSUE TITLE
APSIM.Shared.Utilities.SQLiteException: authorization denied

### ISSUE THREAD

**Issue by SasankhM** [APSIMInitiative/ApsimX#7518]
Getting the following error when trying to run an APSIM simulation:

```
APSIM.Shared.Utilities.SQLiteException: authorization denied
   at APSIM.Shared.Utilities.SQLite.OpenDatabase(String path, Boolean readOnly) in /tmp/ApsimX/APSIM.Shared/Utilities/SQLite.cs:line 424
   at Models.Storage.DataStore.Open() in /tmp/ApsimX/Models/Storage/DataStore.cs:line 247
   at Models.Core.Simulations.SetFileNameInAllSimulations() in /tmp/ApsimX/Models/Core/Simulations.cs:line 190
   at Models.Core.Simulations.Write(String FileName) in /tmp/ApsimX/Models/Core/Simulations.cs:line 176
   at UserInterface.Presenters.ExplorerPresenter.WriteSimulation(String fileName) in /tmp/ApsimX/ApsimNG/Presenters/ExplorerPresenter.cs:line 365
   at UserInterface.Presenters.ExplorerPresenter.Save() in /tmp/ApsimX/ApsimNG/Presenters/ExplorerPresenter.cs:line 321
   at UserInterface.Presenters.MainMenu.OnRun(Object sender, EventArgs e) in /tmp/ApsimX/ApsimNG/Menus/MainMenu.cs:line 198
```

**Comment by peter-devoil** [comment]
Hi - can I ask if this was this running on a mac? And was the .apsimx file in a dropbox or onedrive directory (ie mirrored)? Ta PdeV

**Comment by SasankhM** [comment]
> Hi - can I ask if this was this running on a mac? And was the .apsimx file in a dropbox or onedrive directory (ie mirrored)? Ta PdeV

It was running on a mac and the .apsimx file is on my local drive - thanks!

**Comment by peter-devoil** [comment]
That's one theory shot down - that the network mirroring daemon was locking the file.

**Comment by ric394** [comment]
Does this issue occur with all simulations run on that pc?
Are you able to run another simulation without getting this exception?

**Comment by hol353** [comment]
We need some way to reproduce this problem. Closing the Issue for now. If it is still a problem then feel free to tell us how we can reproduce the problem.
