### ISSUE TITLE
System.Exception: NaN found when getting variable: [Leaf].Fw

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#7656]
I am planting wheat in February in a cold climate. I have replaced the original RUE model with a more complex one. 
I get this error about Fw being NaN. I was wondering if this should ever happen regardless of crop growth conditions.

[APSIM-NG Template.zip](https://github.com/APSIMInitiative/ApsimX/files/10030816/APSIM-NG.Template.zip)

```
ERROR in file: C:\Users\jc837076\OneDrive - James Cook University\00_Projects\2022.09.21 Wheat Ideaotypes in Australia\01_R\APSIM-NG Template\Template.apsimx
Simulation name: Simulation
Models.Core.SimulationException
 ---> System.Exception: Unable to evaluate linear interpolation function .Simulation.Field.Wheat.Structure.HeightModel.WaterStress
 ---> System.Exception: NaN (not a number) found when getting variable: [Leaf].Fw
   at Models.Functions.VariableReference.Value(Int32 arrayIndex) in C:\Users\jc837076\Documents\07_Repository\APSIM NextGen\Models\Functions\VariableReference.cs:line 63
   at Models.Functions.LinearInterpolationFunction.Value(Int32 arrayIndex) in C:\Users\jc837076\Documents\07_Repository\APSIM NextGen\Models\Functions\LinearInterpolationFunction.cs:line 97
   --- End of inner exception stack trace ---
   at Models.Functions.LinearInterpolationFunction.Value(Int32 arrayIndex) in C:\Users\jc837076\Documents\07_Repository\APSIM NextGen\Models\Functions\LinearInterpolationFunction.cs:line 101
   at Models.PMF.Struct.HeightFunction.Value(Int32 arrayIndex) in C:\Users\jc837076\Documents\07_Repository\APSIM NextGen\Models\PMF\Structure\HeightFunction.cs:line 45
   at Models.PMF.Struct.Structure.UpdateHeight() in C:\Users\jc837076\Documents\07_Repository\APSIM NextGen\Models\PMF\Structure\Structure.cs:line 381
   at Models.PMF.Organs.Leaf.OnDoPotentialPlantGrowth(Object sender, EventArgs e) in C:\Users\jc837076\Documents\07_Repository\APSIM NextGen\Models\PMF\Organs\Leaf.cs:line 1244
   at Models.Clock.OnDoCommence(Object sender, CommenceArgs e) in C:\Users\jc837076\Documents\07_Repository\APSIM NextGen\Models\Clock.cs:line 363
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Users\jc837076\Documents\07_Repository\APSIM NextGen\Models\Core\Simulation.cs:line 290
   --- End of inner exception stack trace ---
```

**Comment by BrianCollinss** [comment]
It seems it was attributed to TEC being zero between stages 9 and 10. This has been a default in APSIM Classic, but I am not sure why it causes this problem in NextGen.

![image](https://user-images.githubusercontent.com/39573622/202467278-6bd614d4-6824-4486-aecf-445243f361fe.png)
