### ISSUE TITLE
How to run CroptimizR from APSIMX GUI?

### ISSUE THREAD

**Issue by 12devsilva12** [APSIMInitiative/ApsimX#7697]
I am trying to work through the Optimization Example included in APSIMX. I have Docker running locally, but not sure what setup is required. I have installed CroptimizR from RStudio. I am getting the following error when I try to run the example:

```
System.AggregateException: One or more errors occurred. (Container exited with non-zero exit code. Container log:

Error in loadNamespace(x) : there is no package called 'CroptimizR'
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted

)
 ---> System.Exception: Container exited with non-zero exit code. Container log:

Error in loadNamespace(x) : there is no package called 'CroptimizR'
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted


   at APSIM.Shared.Containers.Docker.RunContainerAsync(String image, String entrypoint, IEnumerable`1 args, IReadOnlyList`1 volumes, Dictionary`2 environment, String workingDir, CancellationToken cancelToken) in /tmp/ApsimX/APSIM.Shared/Containers/Docker.cs:line 134
   at APSIM.Shared.Containers.Docker.RunContainerAsync(String image, String entrypoint, IEnumerable`1 args, IReadOnlyList`1 volumes, Dictionary`2 environment, String workingDir, CancellationToken cancelToken) in /tmp/ApsimX/APSIM.Shared/Containers/Docker.cs:line 149
   at APSIM.Shared.Containers.RDocker.RunScriptAsync(String scriptPath, IEnumerable`1 arguments, CancellationToken cancelToken) in /tmp/ApsimX/APSIM.Shared/Containers/RDocker.cs:line 83
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Models.Optimisation.CroptimizR.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Optimisation/CroptimizR.cs:line 450
   at APSIM.Shared.JobRunning.JobRunner.Run(IRunnable job) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 224
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 189

```
Any advice?

**Comment by john12soil** [comment]
Bumping this question, running into the same issue despite having docker installed? Can anyone please help!

**Comment by hol353** [comment]
@hol430 wrote the Croptimizr module but he has now left us to work elsewhere. I'm not familiar with it at all. I could probably figure it out by looking at the source code but it would take time that I don't have at the moment. Sorry.

**Comment by peter-devoil** [comment]
Same errors occur under linux. Looks to be that the container doesnt contain the stics package. It is being updated (last was 7 days ago) but I dont know where to look for the container build logs, sorry

**Comment by peter-devoil** [comment]
The apsim [docker image](https://hub.docker.com/r/apsiminitiative/apsimng-complete) uses an old version of R (4.1.2), which will no longer build the Stics package:
```
* building 'CroptimizR_0.5.1.tar.gz'
...
ERROR: dependencies 'BayesianTools', 'nloptr' are not available for package 'CroptimizR'
```
I don't get this error on 4.2.2

This appears to be because the [apsimng-r image](https://hub.docker.com/r/apsiminitiative/apsimng-r) (which is used as a layer in apsimng-complete) hasnt been rebuilt for some time. @hol353 - I suspect the jenkins trigger needs to be changed/pulled/whatever here.

**Comment by peter-devoil** [comment]
As a workaround, if you set the environment variable "APSIM_NO_DOCKER" to 1, (eg set the variable in a command window, and start ApsimNG.exe within that window) it will attempt to use your native (4.22?) installation of R instead of the docker image

**Comment by hol353** [comment]
I've updated the APSIM R docker container to use R 4.2.2 and @hol430 added a missing bayesean R package. Does it work now?

**Comment by peter-devoil** [comment]
The example works on linux now. @12devsilva12 can you please check on your windows system, and close the issue if done

**Comment by ric394** [comment]
Not sure if this helps but there is related documentation page located here: https://apsimnextgeneration.netlify.app/usage/croptimizr/

**Comment by par456** [comment]
Using the instructions above, I was able to run the comptimizr example with no errors. Closing this.
