### ISSUE TITLE
CLEM file not being able to do a cleanup. DB not properly written.

### ISSUE THREAD

**Issue by wat-404** [APSIMInitiative/ApsimX#7718]
The error message below is the most common but I've also received ones earlier in the process with other clean up issues. Deleting the *shm, *html, and *.wal seems to help sometimes but not always. I have tried using older (clean??) files, have moved all files to a new 'clean' directory and have upgraded to latest version 7130. 

The file is not able to cleanly write to DB. The Ecol Indicators file is a good example where instead of getting 64 records (4 factors x 16 years) I get 48 or 32 records.

The CLEM file is at https://csiroau.sharepoint.com/:u:/r/sites/CLEMRoWRA/Shared%20Documents/General/CLEM%20parameter%20files/RoRWA%20CLEM%20Scenarios/[CLEM_Roper_Scenario_ALL_EXPERIMENT.apsimx](https://csiroau.sharepoint.com/:u:/r/sites/CLEMRoWRA/Shared%20Documents/General/CLEM%20parameter%20files/RoRWA%20CLEM%20Scenarios/CLEM_Roper_Scenario_ALL_EXPERIMENT.apsimx?csf=1&web=1&e=hi4gza)?csf=1&web=1&e=hi4gza

ERROR in file: X:\aIW\a_RoWRA\CLEM\a_RUNNING(DEC_22)\CLEM_Roper_Scenario_ALL_EXPERIMENT.apsimx
Simulation name: Roper_ExperimentRR02_IrLb_GrEx
Models.Core.SimulationException: Error while performing simulation cleanup
 ---> System.IO.IOException: The process cannot access the file 'X:\aIW\a_RoWRA\CLEM\a_RUNNING(DEC_22)\CLEM_Roper_Scenario_ALL_EXPERIMENT.html' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Models.CLEM.ZoneCLEM.OnCompleted(Object sender, EventArgs e) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\CLEM\ZoneCLEM.cs:line 155
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 307
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 315
   at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Run\SimulationDescription.cs:line 133
   at APSIM.Shared.JobRunning.JobRunner.Run(IRunnable job) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 225
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 189

A different error message but same issue
ERROR in file: X:\aIW\a_RoWRA\CLEM\a_RUNNING(DEC_22)\CLEM_Roper_Scenario_ALL_EXPERIMENT2.apsimx
Simulation name: Roper_ExperimentRR01_IrFS_GrEx
Models.Core.SimulationException
 ---> System.UnauthorizedAccessException: Access to the path 'X:\aIW\a_RoWRA\CLEM\a_RUNNING(DEC_22)\CLEM_Roper_Scenario_ALL_EXPERIMENT2.html' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Models.CLEM.ZoneCLEM.OnSimulationCommencing(Object sender, EventArgs e) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\CLEM\ZoneCLEM.cs:line 143
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 290
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 299
   at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Run\SimulationDescription.cs:line 133
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 213

**Comment by lie112** [comment]
Try and disable the switch to create the descriptive summary automatically for each simulation. This is in CLEM component properties. I believe you are running an experiment with multiple threads and there's a conflict writing this file from each simulation. It is not expected that this file would be generated by each simulation in an experiment.

**Comment by lie112** [comment]
I can reproduce this error and will work on a fix.

**Comment by par456** [comment]
This was fixed in the merge above.
