### ISSUE TITLE
Need a way to see the progress of long-running simulations.

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#7989]
- If there are several simulations of varying length in the 'run', are the quicker simulations being written to the DB file as they go? (the timestamp on the DB file would suggest not)

- if the simulations is stopped from the UI (or killed in TaskManager) it seems that the simulations that have finished are lost.

- Unlike Classic, it seems that it is not possible to see a summary file for a simulation that is in progress. Is there a better way?

At present if a simulation crashes (or is crashed) before completion the error message got when the simulation is reopened is as below and no data is seen

System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Models.Storage.DataStoreReader.GetCheckpointID(String checkpointName) in C:\aaUnderVC\apsimNextGen\Models\Storage\DataStoreReader.cs:line 407
   at UserInterface.Views.PagedDataProvider.GetFilter() in C:\aaUnderVC\apsimNextGen\ApsimNG\Views\Sheet\PagedDataProvider.cs:line 230
   at UserInterface.Views.PagedDataProvider.CreateTemporaryKeyset() in C:\aaUnderVC\apsimNextGen\ApsimNG\Views\Sheet\PagedDataProvider.cs:line 163
   at UserInterface.Views.PagedDataProvider..ctor(IStorageReader store, String checkpointNameInScope, String dataTableName, IEnumerable`1 simulationNamesInScope, String columnNameFilter, String dataFilter, Int32 dataPageSize) in C:\aaUnderVC\apsimNextGen\ApsimNG\Views\Sheet\PagedDataProvider.cs:line 67
   at UserInterface.Presenters.DataStorePresenter.PopulateGrid() in C:\aaUnderVC\apsimNextGen\ApsimNG\Presenters\DataStorePresenter.cs:line 171

**Comment by sno036** [comment]
Not feasible with the current output / datastore mechanism.
