### ISSUE TITLE
SurfaceOrganicMatter operation not in Summary, and removal example

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#8060]
### What happened?

This operation works, but is not reported in the Summary as would be useful:
1996-07-31 [SurfaceOrganicMatter].Add(31300,219,0,Eucalyptus,Eucalyptus)

Also, what is the exact sytnax (example please) for an operation to remove surface organic matter, and would it work if it asks for more biomass to be removed than is present?

### What Operating System are you on?

Windows

**Comment by hol353** [comment]
I have added some code to SurfaceOrganicMatter to report when it adds/removes biomass from the surface.

An example of removing biomass from operations:
```
1900-07-31 [SurfaceOrganicMatter].Remove(20)
```

You specify a mass of biomass in kg/ha. SurfaceOrganicMatter will ensure that mass doesn't fall below zero so you could specify a an amount of biomass that is greater than the current amount of residue and it won't throw an error. It will simply remove all available biomass.

An new installation with these features should be available in about 30 minutes.

**Comment by sme016** [comment]
Thanks

**Comment by sme016** [comment]
Simulation attached: [Slash.zip](https://github.com/APSIMInitiative/ApsimX/files/11963942/Slash.zip)
There might still be a problem. When I do an operation as:
 1998-06-01 [SurfaceOrganicMatter].Remove(20000)

I have the following error message:
ERROR in file: C:\Users\sme016\OneDrive - CSIRO\2a. FWPA EKB\APSIM\Slash\Slash 230705c.apsimx
Simulation name: BussRem
Models.Core.SimulationException
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at APSIM.Shared.Utilities.DateUtilities.ParseDateString(String dateString) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\Utilities\DateUtilities.cs:line 423
   at Models.Operations.OnDoManagement(Object sender, EventArgs e) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Management\Operations.cs:line 85
   at Models.Clock.OnDoCommence(Object _, CommenceArgs e) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Clock.cs:line 344
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 320
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 320
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 213

**Comment by par456** [comment]
I checked the file you sent, in the Operations for the Buss experiement, in variation Rem, the operation has a space at the start of the line which was causing that error. In the short term you can delete that space to get it running again until the fix gets merged in.

**Comment by sme016** [comment]
Thanks for spotting that. Embarrassing for me, sorry. The removal operation works now.
