### ISSUE TITLE
[Soil].Initial.OC lost on move to newer version

### ISSUE THREAD

**Issue by jal-frezie** [APSIMInitiative/ApsimX#8103]
### What happened?

I have a model that ran OK on ApsimX 7040. Now I am trying to run it on ApsimX 7255 and getting the following error:

Models.Core.SimulationException
 ---> System.Exception: Cannot find variable: [Soil].Initial.OC in function: InitialCarbon
   at Models.Functions.ExpressionFunction.FillVariableNames(ExpressionEvaluator fn, Model RelativeTo, Int32 arrayIndex) in /tmp/ApsimX/Models/Functions/ExpressionFunction.cs:line 95
   at Models.Functions.ExpressionFunction.Value(Int32 arrayIndex) in /tmp/ApsimX/Models/Functions/ExpressionFunction.cs:line 52
   at Models.Soils.Nutrients.NutrientPool.Reset() in /tmp/ApsimX/Models/Soils/Nutrients/NutrientPool.cs:line 59
   at Models.Soils.Nutrients.NutrientPool.OnSimulationCommencing(Object sender, EventArgs e) in /tmp/ApsimX/Models/Soils/Nutrients/NutrientPool.cs:line 50
   at Models.Clock.OnDoCommence(Object _, CommenceArgs e) in /tmp/ApsimX/Models/Clock.cs:line 309
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 292
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 301
   at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Run/SimulationDescription.cs:line 133
   at APSIM.Shared.JobRunning.JobRunner.Run(IRunnable job) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 225
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 188
ERRORS FOUND!!

The directory /tmp/ApsimX is deleted immediately so I cannot examine this file. The model contains some manager scripts of my own but they do not refer to this variable.

### What Operating System are you on?

Linux

**Comment by hol353** [comment]
The variable ```[Soil].Initial.OC``` doesn't exist any more. It looks like you have your own copy of the nutrient model in your .apsimx file. If you remove it and re-add Nutrient (through the add model menu) it will then use the released model and the error should disappear. If you still have a problem, please attach a simulation so that we can see what you are doing.

**Comment by par456** [comment]
Going to close this for now, please leave a comment if further information is required and we'll reopen the issue.
