### ISSUE TITLE
Error: "No water and N uptakes supplied to root. Is Soil Arbitrator included in the simulator?" Me: yes it is  

### ISSUE THREAD

**Issue by hrpasl** [APSIMInitiative/ApsimX#8216]
### What happened?

[SoilArbProblem.zip](https://github.com/APSIMInitiative/ApsimX/files/12296849/SoilArbProblem.zip)

ERROR in file: C:\Users\Pas075\OneDrive - CSIRO\Documents\Incubation Sims\GRDC_N_Sites_Field.apsimx
Simulation name: GattonSWRep1
Models.Core.SimulationException
 ---> System.Exception: No water and N uptakes supplied to root. Is Soil Arbitrator included in the simulation?
   at Models.PMF.Organs.Root.SetDryMatterPotentialAllocation(BiomassPoolType dryMatter) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\PMF\Organs\Root.cs:line 634
   at Models.PMF.Arbitrator.SendPotentialDMAllocationsMethod.Calculate(IArbitration[] Organs, BiomassArbitrationType DM, IArbitrationMethod arbitrationMethod) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\PMF\Arbitrator\Methods\SendPotentialDMAllocationsMethod.cs:line 31
   at Models.PMF.BiomassTypeArbitrator.<>c__DisplayClass5_0.<DoPotentialPartitioning>b__0(IPartitionMethod pm) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\PMF\Arbitrator\BiomassTypeArbitrator.cs:line 35
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Models.PMF.BiomassTypeArbitrator.DoPotentialPartitioning(IArbitration[] Organs, BiomassArbitrationType DM) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\PMF\Arbitrator\BiomassTypeArbitrator.cs:line 35
   at Models.PMF.OrganArbitrator.OnDoPotentialPlantPartioning(Object sender, EventArgs e) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\PMF\Arbitrator\OrganArbitrator.cs:line 167
   at Models.Clock.OnDoCommence(Object _, CommenceArgs e) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Clock.cs:line 387
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 292
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 301
   at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Run\SimulationDescription.cs:line 133
   at APSIM.Shared.JobRunning.JobRunner.Run(IRunnable job) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 225
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 188

### What Operating System are you on?

Windows

**Comment by hut104** [comment]
The error message suggests that the soil arbitrator may be missing.  Has this been checked?

**Comment by hrpasl** [comment]
Yes. Also I deleted it and added the model again. It's in the file attached.

**Comment by ilhuber** [comment]
Looks like in your management you are ending Sorghum, then some time later harvesting it leading to this issue. Is this management intentional? Having harvesting occur before end crop on the same day causes the sims to go through. 

Unclear to me why harvesting causes SetDryMatterPotentialAllocation to be called.

**Comment by hrpasl** [comment]
It was intentional, but that's ok. Figured out a work around. Thanks!
