### ISSUE TITLE
Unable to create a new APSIMX file with CLI --apply switch in OneDrive directory.

### ISSUE THREAD

**Issue by ric394** [APSIMInitiative/ApsimX#8254]
### What happened?

I tried to create a new apsimx file using the CLI --apply switch from within OneDrive directory.

got this error:

> C:\Users\RIC394\OneDrive - CSIRO\Documents\Apsim\cli-tutorial-documents>"C:\Program Files\APSIM2023.8.7301.0\bin\Models.exe" --apply commands.txt
> System.Exception: An error occured trying to save a simulation to C:\Users\RIC394\OneDrive - CSIRO\Documents\Apsim\cli-tutorial-documents\cli-example.apsimx            . System.IO.IOException: The filename, directory name, or volume label syntax is incorrect.
>    at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
>    at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
>    at Models.Core.Simulations.Write(String currentFileName, String savePath) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulations.cs:line 187
>    at Models.Core.Simulations.Write(String currentFileName, String savePath) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulations.cs:line 193
>    at Models.Program.Run(Options options) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Main.cs:line 315

Need to make sure file paths like above work in all situations.

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
Closing as it is possible, however quotes need to be used as spaces are present in the path.
