### ISSUE TITLE
Run failed due to Leaf Water stress being set to NaN

### ISSUE THREAD

**Issue by iMarang** [APSIMInitiative/ApsimX#8442]
### What happened?

Details
APSIM next gen 2023.9.7308.0 throws an error on both linux and windows OS (GUI and command line) due to leaf water stress being set to NaN.  Vast majority of runs complete successfully, but this one stood out.

Background
I'm building a wrapper for running wheat and other crops across multiple paddocks/seasons.  Current testing pool is 200 paddocks for both wheat and sorghum, run over 2004-2022.  Each paddock has several management and soil water factors being tested so 729 runs per paddock. The soil water params for each run are based on SLGA data using the conversions in Dalgliesh N. et al. (2016) Field Protocol to APSoil characterisations. Version 4. CSIRO, Australia.

Error (local test):
ERROR in file: C:\Users\marani02\Downloads\CkS3PaXsAANBTrgO_wheat_Carrathool_1817.apsimx
Simulation name: MME
Models.Core.SimulationException
 ---> System.Exception: Unable to evaluate linear interpolation function .MME.Field.Wheat.Structure.HeightModel.WaterStress
 ---> System.Exception: NaN (not a number) found when getting variable: [Leaf].Fw
   at Models.Functions.VariableReference.Value(Int32 arrayIndex) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Functions\VariableReference.cs:line 63
   at Models.Functions.LinearInterpolationFunction.Value(Int32 arrayIndex) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Functions\LinearInterpolationFunction.cs:line 95
   --- End of inner exception stack trace ---
   at Models.Functions.LinearInterpolationFunction.Value(Int32 arrayIndex) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Functions\LinearInterpolationFunction.cs:line 99
   at Models.PMF.Struct.HeightFunction.Value(Int32 arrayIndex) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\PMF\Structure\HeightFunction.cs:line 46
   at Models.PMF.Organs.Leaf.OnDoPotentialPlantGrowth(Object sender, EventArgs e) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\PMF\Organs\Leaf.cs:line 1258
   at Models.Clock.OnDoCommence(Object _, CommenceArgs e) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Clock.cs:line 386
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 292
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 301
   at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Run\SimulationDescription.cs:line 136
   at APSIM.Shared.JobRunning.JobRunner.Run(IRunnable job) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 226
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 189

[CkS3PaXsAANBTrgO_wheat_Carrathool_1817.zip](https://github.com/APSIMInitiative/ApsimX/files/13358563/CkS3PaXsAANBTrgO_wheat_Carrathool_1817.zip)

Any ideas on how the leaf water stress could be set to NaN?   

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
@iMarang I was unable to reproduce the error when running your example on APSIM 2023.10.7336.

**Comment by par456** [comment]
I note your weather file has nothing but NaN values in it which is probably what is causing an error, as a NaN values in the weather could be introduced to a range of calculations. The sim does run on the newest version, but it really shouldn't with that kind of weather file, that seems like a mistake.

You might need to check why the weather file was generated like this.

![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/2cc9d304-c3c9-4e7e-a534-81109cadb2f4)

**Comment by iMarang** [comment]
Ah, thanks for looking into this.  Apologies for wasting your time, I should've checked that, the run files work fine with alternate weather inputs.  I'll back away quietly now.
