### ISSUE TITLE
APSIM.Server crashes with System.NotSupportedException

### ISSUE THREAD

**Issue by cjosephson** [APSIMInitiative/ApsimX#8446]
### What happened?

Invoking the server with `dotnet run --project APSIM.Server/V1/APSIM.Server.csproj --framework net8.0 -- -f Examples/Potato.apsimx` leads to the following error:

```
System.Exception: Error reading file Examples/Potato.apsimx
 ---> System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at APSIM.Shared.Utilities.ReflectionUtilities.BinarySerialise(Object source, SerializationBinder binder) in /Users/cjosephson/oasis_sim/APSIM.Shared/Utilities/ReflectionUtilities.cs:line 333
   at APSIM.Shared.Utilities.ReflectionUtilities.Clone(Object sourceObj) in /Users/cjosephson/oasis_sim/APSIM.Shared/Utilities/ReflectionUtilities.cs:line 562
   at Models.Core.Apsim.Clone[T](T model) in /Users/cjosephson/oasis_sim/Models/Core/Apsim.cs:line 65
   at Models.Core.Resource.GetModel(String resourceName) in /Users/cjosephson/oasis_sim/Models/Core/Resource.cs:line 125
   at Models.Core.Resource.ReplaceModel(IModel model, Boolean enabled) in /Users/cjosephson/oasis_sim/Models/Core/Resource.cs:line 50
   at Models.Core.Resource.Replace(IModel model) in /Users/cjosephson/oasis_sim/Models/Core/Resource.cs:line 114
   at Models.Core.ApsimFile.FileFormat.ReadFromString[T](String st, Action`1 errorHandler, Boolean initInBackground, String fileName) in /Users/cjosephson/oasis_sim/Models/Core/ApsimFile/FileFormat.cs:line 115
   at Models.Core.ApsimFile.FileFormat.ReadFromFile[T](String fileName, Action`1 errorHandler, Boolean initInBackground) in /Users/cjosephson/oasis_sim/Models/Core/ApsimFile/FileFormat.cs:line 66
   --- End of inner exception stack trace ---
   at Models.Core.ApsimFile.FileFormat.ReadFromFile[T](String fileName, Action`1 errorHandler, Boolean initInBackground) in /Users/cjosephson/oasis_sim/Models/Core/ApsimFile/FileFormat.cs:line 78
   at APSIM.Server.ApsimServer..ctor(GlobalServerOptions options) in /Users/cjosephson/oasis_sim/APSIM.Server/V1/ApsimServer.cs:line 42
   at APSIM.Server.Program.Run(GlobalServerOptions options) in /Users/cjosephson/oasis_sim/APSIM.Server/V1/Program.cs:line 39

```

The error appears to be the same for all the .apsimx files in the Examples directory. Running on a Mac with Ventura 13.4.1 installed

The server is built from source, and the build command `dotnet build -c Debug ApsimX.sln` ran with no errors or warnings. 

### What Operating System are you on?

MacOS

**Comment by zur003** [comment]
See [https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md) for the status of "BinaryFormatter" in various versions of .Net. It appears that .Net 8 requires a <EnableUnsafeBinaryFormatterSerialization> switch in the project file for "BinaryFormatter" to work.

**Comment by cjosephson** [comment]
Yes. I was able to work around it temporarily by adding 

`   <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
`

to the `<PropertyGroup>`

**Comment by par456** [comment]
This is a solution for the short term, so I'll close this issue and we can discuss the long term solution to replacing BinaryFormatter in #8680 where we can keep all the discussion together.
