### ISSUE TITLE
Order of config file when using --apply switch is important

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#8471]
### What happened?

When running the .apsimx file in the attached zip file, the following error happens:
```
C:\Work\Temp>C:\Work\Repos\ApsimInitiative\ApsimX\bin\Debug\net6.0\Models.exe --apply commands.txt test.apsimx
----------------------------------------------
ERROR in file: C:\Work\Temp\testtemp.apsimx
Simulation name: Simulation
Models.Core.SimulationException
 ---> Models.Core.ApsimXException: Cannot find weather file 'emerald.met'
   at Models.Climate.Weather.GetMetData(DateTime date) in C:\Work\Repos\ApsimInitiative\ApsimX\Models\Climate\Weather.cs:line 711
   at Models.Climate.Weather.OnDoWeather(Object sender, EventArgs e) in C:\Work\Repos\ApsimInitiative\ApsimX\Models\Climate\Weather.cs:line 644
   at Models.Clock.OnDoCommence(Object _, CommenceArgs e) in C:\Work\Repos\ApsimInitiative\ApsimX\Models\Clock.cs:line 337
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Work\Repos\ApsimInitiative\ApsimX\Models\Core\Simulation.cs:line 292
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Work\Repos\ApsimInitiative\ApsimX\Models\Core\Simulation.cs:line 301
   at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in C:\Work\Repos\ApsimInitiative\ApsimX\Models\Core\Run\SimulationDescription.cs:line 136
   at APSIM.Shared.JobRunning.JobRunner.Run(IRunnable job) in C:\Work\Repos\ApsimInitiative\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 232
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in C:\Work\Repos\ApsimInitiative\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 195
```

The commands.txt file looks like this:
```
[Weather].FileName=dalby.met
[Soil] = GSGApsoilAdjusted.apsimx;[179]
run
```

The problem is that the weather filename set line is being ignored. If you reverse the first and second lines of commands.txt then it works.

The other problem is that I expected the .db file to be called test.db because that is the file I opened on the command line. Instead, it is called testnew.db.

[test.zip](https://github.com/APSIMInitiative/ApsimX/files/13480523/test.zip)

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
Addressing the second issue, because a save command was not included, the changes are only made to a temporary version of the simulation. This should explain why they are only in the testtemp.db file.
