### ISSUE TITLE
CroptimizeR tries to run Models.dll instead of Models.exe

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8512]
### What happened?
Without the docker:
```
Error from R:
Script path: 'C:\Users\U8019357\AppData\Local\Temp\CroptimizR-63415111-a94e-44c8-80bc-fed4ab6f67ee\parameter_estimation.r'
StdErr:
Learn CroptimizR at: https://SticsRPacks.github.io/CroptimizR
Attaching package: 'CroptimizR'
The following objects are masked from 'package:stats':
    AIC, BIC
Attaching package: 'dplyr'
The following objects are masked from 'package:stats':
    filter, lag
The following objects are masked from 'package:base':
    intersect, setdiff, setequal, union
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-C:/Users/U8019357/OneDrive does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
Error in apsimx_wrapper(model_options = model_options) : 
  C:/Users/U8019357/OneDrive - UniSQ/Documents/Repository/APSIMNextGen/bin/Debug/net6.0/Models.dll is not executable or is not a apsimx executable !
In addition: Warning message:
In system(cmd, wait = TRUE, intern = TRUE) :
  running command 'dotnet C:/Users/U8019357/OneDrive - UniSQ/Documents/Repository/APSIMNextGen/bin/Debug/net6.0/Models.dll /Version' had status 1
Execution halted
```

With the docker:
```
System.AggregateException: One or more errors occurred. (Docker API responded with status code=Conflict, response={"message":"Cannot kill container: 9c25ecc48b5e01ff9b86961df0b61fcc66a00dcab4317f39aab9d2b8cc30e103: Container 9c25ecc48b5e01ff9b86961df0b61fcc66a00dcab4317f39aab9d2b8cc30e103 is not running"}
)
 ---> Docker.DotNet.DockerApiException: Docker API responded with status code=Conflict, response={"message":"Cannot kill container: 9c25ecc48b5e01ff9b86961df0b61fcc66a00dcab4317f39aab9d2b8cc30e103: Container 9c25ecc48b5e01ff9b86961df0b61fcc66a00dcab4317f39aab9d2b8cc30e103 is not running"}

   at Docker.DotNet.DockerClient.HandleIfErrorResponseAsync(HttpStatusCode statusCode, HttpResponseMessage response, IEnumerable`1 handlers)
   at Docker.DotNet.DockerClient.MakeRequestAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
   at APSIM.Shared.Containers.Docker.RunContainerAsync(String image, String entrypoint, IEnumerable`1 args, IReadOnlyList`1 volumes, Dictionary`2 environment, String workingDir, CancellationToken cancelToken) in C:\Users\U8019357\OneDrive - UniSQ\Documents\Repository\APSIMNextGen\APSIM.Shared\Containers\Docker.cs:line 147
   at APSIM.Shared.Containers.RDocker.RunScriptAsync(String scriptPath, IEnumerable`1 arguments, CancellationToken cancelToken) in C:\Users\U8019357\OneDrive - UniSQ\Documents\Repository\APSIMNextGen\APSIM.Shared\Containers\RDocker.cs:line 83
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Models.Optimisation.CroptimizR.Run(CancellationTokenSource cancelToken) in C:\Users\U8019357\OneDrive - UniSQ\Documents\Repository\APSIMNextGen\Models\Optimisation\CroptimizR.cs:line 452
   at APSIM.Shared.JobRunning.JobRunner.Run(IRunnable job) in C:\Users\U8019357\OneDrive - UniSQ\Documents\Repository\APSIMNextGen\APSIM.Shared\JobRunning\JobRunner.cs:line 226
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in C:\Users\U8019357\OneDrive - UniSQ\Documents\Repository\APSIMNextGen\APSIM.Shared\JobRunning\JobRunner.cs:line 189
```

### What Operating System are you on?

Windows

**Comment by ilhuber** [comment]
This is correct, right? Calling dotnet on Models.dll is essentially the same as calling Models.exe here. The error message might have to do with spaces in path. May be related to APSIMInitiative/ApsimOnR#4.

**Comment by BrianCollinss** [comment]
Was it (the issue with the spaces in the path) not supposed to be solved by [this PR](https://github.com/APSIMInitiative/ApsimOnR/pull/5)?

**Comment by ilhuber** [comment]
It seems to resolve it, though the PR has not been merged unfortunately.

**Comment by hol353** [comment]
Merged now. Sorry for the huge delay. That PR fell through the cracks.

**Comment by BrianCollinss** [comment]
Thanks Dean for keeping eye on everything :)
