### ISSUE TITLE
Export to Excel generates error

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#8659]
### What happened?

The Excel file is created but the user is shown the error message below

System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.Packaging, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.IO.Packaging, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at ClosedXML.Excel.XLWorkbook.SetPackageProperties(OpenXmlPackage document)
   at ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, SaveOptions options)
   at Utility.Excel.WriteToEXCEL(DataTable[] tables, String fileName) in C:\aaUnderVC\ApsimX\ApsimNG\Utility\Excel.cs:line 34
   at UserInterface.Presenters.ContextMenu.<>c__DisplayClass30_1.<ExportDataStoreToEXCEL>b__3() in C:\aaUnderVC\ApsimX\ApsimNG\Menus\ContextMenu.cs:line 697
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at UserInterface.Presenters.ContextMenu.ExportDataStoreToEXCEL(Object sender, EventArgs e) in C:\aaUnderVC\ApsimX\ApsimNG\Menus\ContextMenu.cs:line 700

![image](https://github.com/APSIMInitiative/ApsimX/assets/12176269/027c7ebb-00da-4353-8d4b-d32ea157da89)

### What Operating System are you on?

Windows

**Comment by par456** [comment]
I think I know what this is, will investigate further.
