### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Tao1991** [APSIMInitiative/ApsimX#8712]
### What happened?

Simulation name: Chickpea
Models.Core.SimulationException
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Models.Script.OnDoManagement(Object sender, EventArgs e)
   at Models.Clock.OnDoCommence(Object _, CommenceArgs e) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Clock.cs:line 359
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 292
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 301
   at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Run\SimulationDescription.cs:line 136
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 214

### What Operating System are you on?

Windows

**Comment by par456** [comment]
Could you put your apsimx file into a .zip folder and upload it to a post here? That'll make it easier for us to know what is going wrong in your file.

**Comment by Tao1991** [comment]
Hi Andrew, When I set up and run model following the Module 5 ( APSIM Next Generation ), it gives a error "Object reference not set to an instance of an object." Please see the attachment for apsimx file. Please let me know if you need other materials. Regards, Tao On 29 Feb 2024, at 6:46, Andrew Paroz ***@***.***> wrote: Could you put your apsimx file into a .zip folder and upload it to a post here? That'll make it easier for us to know what is going wrong in your file. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>
