### ISSUE TITLE
 SWIM3 not working with Canola 

### ISSUE THREAD

**Issue by Kadogo1** [APSIMInitiative/ApsimX#8736]
### What happened?

I'm running the Canola Example (from APSIM Examples folder) with SWIM3 in APSIM NG v7349 but it fails with the message "A canopy was found that isn't a plant. Name: EnergyBalance" A similar issue was raised in the past and it appears closed (solved) but the model still gives an error. How can I get SWIM3 to work with v7349.0?
Thanks

The full error message is as shown below.
Models.Core.SimulationException
 ---> System.Exception: A canopy was found that isn't a plant. Name: EnergyBalance
   at Models.Soils.Swim3.GetCropVariables() in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Soils\SWIM\Swim.cs:line 1888
   at Models.Soils.Swim3.OnProcess() in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Soils\SWIM\Swim.cs:line 1179
   at Models.Soils.Swim3.OnDoSoilWaterMovement(Object sender, EventArgs e) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Soils\SWIM\Swim.cs:line 1155
   at Models.Clock.OnDoCommence(Object _, CommenceArgs e) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Clock.cs:line 360
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 320
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 320
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 214

### What Operating System are you on?

Windows

**Comment by par456** [comment]
The current apsim version is 7419, so you should just need to update to the newer version (use the update button within the program), as the bug causing this was only found and fixed a few weeks ago.

**Comment by Kadogo1** [comment]
So there is no way to get the lower version to work with swim3 apart from upgrading it?
Thanks

**Comment by par456** [comment]
Unfortunately not, is there a reason you have to stick with the older version?

**Comment by Kadogo1** [comment]
I prefer to stick with the older version because our team has been using that version for different crops and we need to compare results using the same model version.
Thanks
