### ISSUE TITLE
TreeeProxy temporal data entry not possible

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#8856]
### What happened?

The TreeProxy of the Agroforestry TreeBeltExample is not allowing data overwriting for Temporal Data by manual typing or copy-paste from elsewhere. I'd apprecaite this fixed ASAP, as I need this working to help colleagues in Vietnam with their simulations. Copying and pasting a TreeProxy node from a previous simulation that worked several months ago, also does not work. 
Here is the example freshly downloaded frrom the GUI with the latest release (7452):
[TreeBeltExample5.zip](https://github.com/APSIMInitiative/ApsimX/files/15023851/TreeBeltExample5.zip)

### What Operating System are you on?

Windows

**Comment by par456** [comment]
Tree Spatial also has errors

**Comment by sme016** [comment]
Thanks, but it's still not working. The dates are editable, but the display of the temporal and spatial data have been swapped between the Temporal and Spatial data tabs and the error message is:
ERROR in file: C:\Users\sme016\OneDrive - CSIRO\1. Rafael Visit 2023\APSIM Training Workshop\Sims\TreeBeltExampleTest.apsimx
Simulation name: Tree Belt Example
Models.Core.SimulationException
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Models.Agroforestry.TreeProxy.SetupTreeProperties() in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Agroforestry\TreeProxy.cs:line 482
   at Models.Agroforestry.TreeProxy.OnSimulationCommencing(Object sender, EventArgs e) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Agroforestry\TreeProxy.cs:line 584
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 292
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 304
   at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Run\SimulationDescription.cs:line 136
   at APSIM.Shared.JobRunning.JobRunner.Run(IRunnable job) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 226
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 189
