### ISSUE TITLE
Sorghum model senescence defect

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#8917]
### What happened?

The attached simulation throws the exception:

```
Paddock.Sorghum.Leaf:                             Emergence
                                                  LAI = 0.00 (m^2/m^2)
Paddock.Sorghum.AboveGround:                      AboveGround = 1.80 (g/m^2)
.Sorghum_DEWS-30778_Northern_Soil_72_Pop9_Buster: ERROR in file: C:\Work\Temp\Heidi\Sorghum_Pop9_30778.apsimx
Simulation name: Sorghum_DEWS-30778_Northern_Soil_72_Pop9_Buster
Models.Core.SimulationException
 ---> System.Exception: Attempted to senesce more N than exists on leaf 'Leaf'
   at Models.PMF.Organs.SorghumLeaf.ApplySenescence() in C:\Work\Repos\APSIMInitiative\ApsimX\Models\PMF\Organs\SorghumLeaf.cs:line 897
   at Models.PMF.Organs.SorghumLeaf.OnDoActualPlantGrowth(Object sender, EventArgs e) in C:\Work\Repos\APSIMInitiative\ApsimX\Models\PMF\Organs\SorghumLeaf.cs:line 1102
   at Models.Clock.OnDoCommence(Object _, CommenceArgs e) in C:\Work\Repos\APSIMInitiative\ApsimX\Models\Clock.cs:line 417
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in C:\Work\Repos\APSIMInitiative\ApsimX\Models\Core\Simulation.cs:line 292
   --- End of inner exception stack trace ---
```

135.8 kg/ha of NO3N was added at sowing. The sorghum model is trying to senesce all leaves at emergence so my guess it is severley water stresed.

[Sorghum_Pop9_30778.zip](https://github.com/APSIMInitiative/ApsimX/files/15287949/Sorghum_Pop9_30778.zip)

### What Operating System are you on?

Windows

**Comment by hol353** [comment]
@peter-devoil - can you look at this?
