### ISSUE TITLE
Random error from Download Soil

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8963]
### What happened?

Sometimes I get this error when I import a soil from the Soil Download window. It does not sound like a soil thing!

`Graph scope is incorrect if placed under a Simulation in an Experiment. It should be a child of the Experiment instead.`

```
System.Exception: Graph scope is incorrect if placed under a Simulation in an Experiment. It should be a child of the Experiment instead.
   at Models.GraphPage.FindSimulationDescriptions(IModel model) in \APSIMNextGen\Models\Graph\GraphPage.cs:line 72
   at Models.GraphPage.GetAllSeriesDefinitions(IModel parent, IStorageReader storage, List`1 simulationFilter) in \APSIMNextGen\Models\Graph\GraphPage.cs:line 34
   at UserInterface.Presenters.GraphPresenter.DrawGraph() in \APSIMNextGen\ApsimNG\Presenters\GraphPresenter.cs:line 107
   at UserInterface.Presenters.GraphPresenter.Attach(Object model, Object view, ExplorerPresenter explorerPresenter, List`1 cache) in \APSIMNextGen\ApsimNG\Presenters\GraphPresenter.cs:line 70
   at UserInterface.Presenters.GraphPresenter.Attach(Object model, Object view, ExplorerPresenter explorerPresenter) in \APSIMNextGen\ApsimNG\Presenters\GraphPresenter.cs:line 48
   at UserInterface.Presenters.ExplorerPresenter.ShowInRightHandPanel(Object model, ViewBase newView, IPresenter presenter) in \APSIMNextGen\ApsimNG\Presenters\ExplorerPresenter.cs:line 841
   at UserInterface.Presenters.ExplorerPresenter.ShowInRightHandPanel(Object model, String viewName, String presenterName) in \APSIMNextGen\ApsimNG\Presenters\ExplorerPresenter.cs:line 804
   at UserInterface.Presenters.ExplorerPresenter.ShowRightHandPanel() in \APSIMNextGen\ApsimNG\Presenters\ExplorerPresenter.cs:line 787
   at UserInterface.Presenters.ExplorerPresenter.OnNodeSelected(Object sender, NodeSelectedArgs e) in \APSIMNextGen\ApsimNG\Presenters\ExplorerPresenter.cs:line 952
```

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
@BrianCollinss This error appears because the node tree is refreshed after adding a soil. You're right that it isn't directly related to soils. But this normal.

**Comment by BrianCollinss** [comment]
Thanks @ric394 . Does it mean there is an issue somewhere else?

**Comment by ric394** [comment]
@BrianCollinss Only that there is an issue with the correct file being used.
