### ISSUE TITLE
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by smkuhlani** [APSIMInitiative/ApsimX#9448]
### What happened?

We are attempting to run Apsim new generation simulations in linux environment, using the apsimx R package. The same file or worklfow runs in windows. We are running these attached input files: 

[apsim_example_files.zip](https://github.com/user-attachments/files/17745180/apsim_example_files.zip)

We are running the files attOn running the same apsimx file in R produces the error(s) below:

 at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 295
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 307
   at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Run/SimulationDescription.cs:line 136
   at APSIM.Shared.JobRunning.JobRunner.Run(IRunnable job) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 226
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 189
----------------------------------------------
ERROR in file: ./MaizeFactorialAugSep.apsimx
Simulation name: pdSowDate28-oct
Models.Core.SimulationException
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at APSIM.Shared.Utilities.MathUtilities.Divide(Double[] value1, Double[] value2, Double errVal) in /tmp/ApsimX/APSIM.Shared/Utilities/MathUtilities.cs:line 153
   at Models.Soils.Organic.get_CNR() in /tmp/ApsimX/Models/Soils/Organic.cs:line 102
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Models.Core.VariableProperty.get_Value() in /tmp/ApsimX/Models/Core/VariableProperty.cs:line 361
   at Models.Core.Locator.GetInternal(String namePath, LocatorFlags flags) in /tmp/ApsimX/Models/Core/Locator.cs:line 250
   at Models.Functions.ExpressionFunction.FillVariableNames(ExpressionEvaluator fn, Model RelativeTo, Int32 arrayIndex) in /tmp/ApsimX/Models/Functions/ExpressionFunction.cs:line 84
   at Models.Functions.ExpressionFunction.Value(Int32 arrayIndex) in /tmp/ApsimX/Models/Functions/ExpressionFunction.cs:line 52
   at Models.Soils.Nutrients.OrganicPool.Initialise(Int32 numberLayers) in /tmp/ApsimX/Models/Soils/Nutrients/OrganicPool.cs:line 87
   at Models.Soils.Nutrients.Nutrient.Reset() in /tmp/ApsimX/Models/Soils/Nutrients/Nutrient.cs:line 269
   at Models.Soils.Nutrients.Nutrient.OnCommencing(Object sender, EventArgs e) in /tmp/ApsimX/Models/Soils/Nutrients/Nutrient.cs:line 318
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 295
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 307
   at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Run/SimulationDescription.cs:line 136
   at APSIM.Shared.JobRunning.JobRunner.Run(IRunnable job) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 226
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 189
----------------------------------------------
ERROR in file: ./MaizeFactorialAugSep.apsimx
Simulation name: pdSowDate16-sep
Models.Core.SimulationException
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at APSIM.Shared.Utilities.MathUtilities.Divide(Double[] value1, Double[] value2, Double errVal) in /tmp/ApsimX/APSIM.Shared/Utilities/MathUtilities.cs:line 153
   at Models.Soils.Organic.get_CNR() in /tmp/ApsimX/Models/Soils/Organic.cs:line 102
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Models.Core.VariableProperty.get_Value() in /tmp/ApsimX/Models/Core/VariableProperty.cs:line 361
   at Models.Core.Locator.GetInternal(String namePath, LocatorFlags flags) in /tmp/ApsimX/Models/Core/Locator.cs:line 250
   at Models.Functions.ExpressionFunction.FillVariableNames(ExpressionEvaluator fn, Model RelativeTo, Int32 arrayIndex) in /tmp/ApsimX/Models/Functions/ExpressionFunction.cs:line 84
   at Models.Functions.ExpressionFunction.Value(Int32 arrayIndex) in /tmp/ApsimX/Models/Functions/ExpressionFunction.cs:line 52
   at Models.Soils.Nutrients.OrganicPool.Initialise(Int32 numberLayers) in /tmp/ApsimX/Models/Soils/Nutrients/OrganicPool.cs:line 87
   at Models.Soils.Nutrients.Nutrient.Reset() in /tmp/ApsimX/Models/Soils/Nutrients/Nutrient.cs:line 269
   at Models.Soils.Nutrients.Nutrient.OnCommencing(Object sender, EventArgs e) in /tmp/ApsimX/Models/Soils/Nutrients/Nutrient.cs:line 318
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 295
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 307
   at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Run/SimulationDescription.cs:line 136
   at APSIM.Shared.JobRunning.JobRunner.Run(IRunnable job) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 226
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 189
----------------------------------------------
ERROR in file: ./MaizeFactorialAugSep.apsimx
Simulation name: pdSowDate07-oct
Models.Core.SimulationException
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at APSIM.Shared.Utilities.MathUtilities.Divide(Double[] value1, Double[] value2, Double errVal) in /tmp/ApsimX/APSIM.Shared/Utilities/MathUtilities.cs:line 153
   at Models.Soils.Organic.get_CNR() in /tmp/ApsimX/Models/Soils/Organic.cs:line 102
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Models.Core.VariableProperty.get_Value() in /tmp/ApsimX/Models/Core/VariableProperty.cs:line 361
   at Models.Core.Locator.GetInternal(String namePath, LocatorFlags flags) in /tmp/ApsimX/Models/Core/Locator.cs:line 250
   at Models.Functions.ExpressionFunction.FillVariableNames(ExpressionEvaluator fn, Model RelativeTo, Int32 arrayIndex) in /tmp/ApsimX/Models/Functions/ExpressionFunction.cs:line 84
   at Models.Functions.ExpressionFunction.Value(Int32 arrayIndex) in /tmp/ApsimX/Models/Functions/ExpressionFunction.cs:line 52
   at Models.Soils.Nutrients.OrganicPool.Initialise(Int32 numberLayers) in /tmp/ApsimX/Models/Soils/Nutrients/OrganicPool.cs:line 87
   at Models.Soils.Nutrients.Nutrient.Reset() in /tmp/ApsimX/Models/Soils/Nutrients/Nutrient.cs:line 269
   at Models.Soils.Nutrients.Nutrient.OnCommencing(Object sender, EventArgs e) in /tmp/ApsimX/Models/Soils/Nutrients/Nutrient.cs:line 318
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 295
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 307
   at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Run/SimulationDescription.cs:line 136
   at APSIM.Shared.JobRunning.JobRunner.Run(IRunnable job) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 226
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 189

----------------------------------------------
ERRORS FOUND!!

### What Operating System are you on?

Windows

**Comment by smkuhlani** [comment]
> ### What happened?
> 
> We are attempting to run Apsim new generation simulations in linux environment, using the apsimx R package. The same file or worklfow runs in windows. We are running these attached input files:
> 
> [apsim_example_files.zip](https://github.com/user-attachments/files/17745180/apsim_example_files.zip)
> 
> We are running the files attOn running the same apsimx file in R produces the error(s) below:
> ## at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 295
> --- End of inner exception stack trace ---
> at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 307
> at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Run/SimulationDescription.cs:line 136
> at APSIM.Shared.JobRunning.JobRunner.Run(IRunnable job) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 226
> at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 189
> ## ERROR in file: ./MaizeFactorialAugSep.apsimx
> Simulation name: pdSowDate28-oct
> Models.Core.SimulationException
> ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
> ---> System.NullReferenceException: Object reference not set to an instance of an object.
> at APSIM.Shared.Utilities.MathUtilities.Divide(Double[] value1, Double[] value2, Double errVal) in /tmp/ApsimX/APSIM.Shared/Utilities/MathUtilities.cs:line 153
> at Models.Soils.Organic.get_CNR() in /tmp/ApsimX/Models/Soils/Organic.cs:line 102
> --- End of inner exception stack trace ---
> at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
> at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
> at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
> at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
> at Models.Core.VariableProperty.get_Value() in /tmp/ApsimX/Models/Core/VariableProperty.cs:line 361
> at Models.Core.Locator.GetInternal(String namePath, LocatorFlags flags) in /tmp/ApsimX/Models/Core/Locator.cs:line 250
> at Models.Functions.ExpressionFunction.FillVariableNames(ExpressionEvaluator fn, Model RelativeTo, Int32 arrayIndex) in /tmp/ApsimX/Models/Functions/ExpressionFunction.cs:line 84
> at Models.Functions.ExpressionFunction.Value(Int32 arrayIndex) in /tmp/ApsimX/Models/Functions/ExpressionFunction.cs:line 52
> at Models.Soils.Nutrients.OrganicPool.Initialise(Int32 numberLayers) in /tmp/ApsimX/Models/Soils/Nutrients/OrganicPool.cs:line 87
> at Models.Soils.Nutrients.Nutrient.Reset() in /tmp/ApsimX/Models/Soils/Nutrients/Nutrient.cs:line 269
> at Models.Soils.Nutrients.Nutrient.OnCommencing(Object sender, EventArgs e) in /tmp/ApsimX/Models/Soils/Nutrients/Nutrient.cs:line 318
> at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 295
> --- End of inner exception stack trace ---
> at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 307
> at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Run/SimulationDescription.cs:line 136
> at APSIM.Shared.JobRunning.JobRunner.Run(IRunnable job) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 226
> at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 189
> ## ERROR in file: ./MaizeFactorialAugSep.apsimx
> Simulation name: pdSowDate16-sep
> Models.Core.SimulationException
> ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
> ---> System.NullReferenceException: Object reference not set to an instance of an object.
> at APSIM.Shared.Utilities.MathUtilities.Divide(Double[] value1, Double[] value2, Double errVal) in /tmp/ApsimX/APSIM.Shared/Utilities/MathUtilities.cs:line 153
> at Models.Soils.Organic.get_CNR() in /tmp/ApsimX/Models/Soils/Organic.cs:line 102
> --- End of inner exception stack trace ---
> at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
> at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
> at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
> at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
> at Models.Core.VariableProperty.get_Value() in /tmp/ApsimX/Models/Core/VariableProperty.cs:line 361
> at Models.Core.Locator.GetInternal(String namePath, LocatorFlags flags) in /tmp/ApsimX/Models/Core/Locator.cs:line 250
> at Models.Functions.ExpressionFunction.FillVariableNames(ExpressionEvaluator fn, Model RelativeTo, Int32 arrayIndex) in /tmp/ApsimX/Models/Functions/ExpressionFunction.cs:line 84
> at Models.Functions.ExpressionFunction.Value(Int32 arrayIndex) in /tmp/ApsimX/Models/Functions/ExpressionFunction.cs:line 52
> at Models.Soils.Nutrients.OrganicPool.Initialise(Int32 numberLayers) in /tmp/ApsimX/Models/Soils/Nutrients/OrganicPool.cs:line 87
> at Models.Soils.Nutrients.Nutrient.Reset() in /tmp/ApsimX/Models/Soils/Nutrients/Nutrient.cs:line 269
> at Models.Soils.Nutrients.Nutrient.OnCommencing(Object sender, EventArgs e) in /tmp/ApsimX/Models/Soils/Nutrients/Nutrient.cs:line 318
> at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 295
> --- End of inner exception stack trace ---
> at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 307
> at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Run/SimulationDescription.cs:line 136
> at APSIM.Shared.JobRunning.JobRunner.Run(IRunnable job) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 226
> at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 189
> 
> ERROR in file: ./MaizeFactorialAugSep.apsimx Simulation name: pdSowDate07-oct Models.Core.SimulationException ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object. at APSIM.Shared.Utilities.MathUtilities.Divide(Double[] value1, Double[] value2, Double errVal) in /tmp/ApsimX/APSIM.Shared/Utilities/MathUtilities.cs:line 153 at Models.Soils.Organic.get_CNR() in /tmp/ApsimX/Models/Soils/Organic.cs:line 102 --- End of inner exception stack trace --- at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture) at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index) at Models.Core.VariableProperty.get_Value() in /tmp/ApsimX/Models/Core/VariableProperty.cs:line 361 at Models.Core.Locator.GetInternal(String namePath, LocatorFlags flags) in /tmp/ApsimX/Models/Core/Locator.cs:line 250 at Models.Functions.ExpressionFunction.FillVariableNames(ExpressionEvaluator fn, Model RelativeTo, Int32 arrayIndex) in /tmp/ApsimX/Models/Functions/ExpressionFunction.cs:line 84 at Models.Functions.ExpressionFunction.Value(Int32 arrayIndex) in /tmp/ApsimX/Models/Functions/ExpressionFunction.cs:line 52 at Models.Soils.Nutrients.OrganicPool.Initialise(Int32 numberLayers) in /tmp/ApsimX/Models/Soils/Nutrients/OrganicPool.cs:line 87 at Models.Soils.Nutrients.Nutrient.Reset() in /tmp/ApsimX/Models/Soils/Nutrients/Nutrient.cs:line 269 at Models.Soils.Nutrients.Nutrient.OnCommencing(Object sender, EventArgs e) in /tmp/ApsimX/Models/Soils/Nutrients/Nutrient.cs:line 318 at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 295 --- End of inner exception stack trace --- at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 307 at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Run/SimulationDescription.cs:line 136 at APSIM.Shared.JobRunning.JobRunner.Run(IRunnable job) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 226 at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 189
> 
> ERRORS FOUND!!
> ### What Operating System are you on?
> 
> Windows

**Comment by peter-devoil** [comment]
I suspect you'll need to define your CN ratio and initial FOM pools:
![image](https://github.com/user-attachments/assets/295dc76c-1684-4e30-8c1a-c8da5eb6f0ab)

**Comment by lpmorenoc** [comment]
@peter-devoil, are those values needed even if we run under water-limited conditions? Also, the error we encountered with @smkuhlani was trying to run APSIM in Linux; however, the model could run in Windows.

**Comment by peter-devoil** [comment]
a) yes, they are needed, b) that's unusual - its the same code on the same runtime.

**Comment by smkuhlani** [comment]
Thanks. We filled in the CN ratio and FOM, but we have new errors.

[apsim_example_files.zip](https://github.com/user-attachments/files/17841106/apsim_example_files.zip)


ERROR in file: ./MaizeFactorialAugSep.apsimx
Simulation name: pdSowDate28-oct
Models.Core.SimulationException
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at APSIM.Shared.Utilities.MathUtilities.Divide(Double[] value1, Double[] value2, Double errVal) in /tmp/ApsimX/APSIM.Shared/Utilities/MathUtilities.cs:line 153
   at Models.Soils.Organic.get_CNR() in /tmp/ApsimX/Models/Soils/Organic.cs:line 102
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Models.Core.VariableProperty.get_Value() in /tmp/ApsimX/Models/Core/VariableProperty.cs:line 361
   at Models.Core.Locator.GetInternal(String namePath, LocatorFlags flags) in /tmp/ApsimX/Models/Core/Locator.cs:line 250
   at Models.Functions.ExpressionFunction.FillVariableNames(ExpressionEvaluator fn, Model RelativeTo, Int32 arrayIndex) in /tmp/ApsimX/Models/Functions/ExpressionFunction.cs:line 84
   at Models.Functions.ExpressionFunction.Value(Int32 arrayIndex) in /tmp/ApsimX/Models/Functions/ExpressionFunction.cs:line 52
   at Models.Soils.Nutrients.OrganicPool.Initialise(Int32 numberLayers) in /tmp/ApsimX/Models/Soils/Nutrients/OrganicPool.cs:line 87
   at Models.Soils.Nutrients.Nutrient.Reset() in /tmp/ApsimX/Models/Soils/Nutrients/Nutrient.cs:line 269
   at Models.Soils.Nutrients.Nutrient.OnCommencing(Object sender, EventArgs e) in /tmp/ApsimX/Models/Soils/Nutrients/Nutrient.cs:line 318
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 295
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 307
   at Models.Core.Run.SimulationDescription.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Run/SimulationDescription.cs:line 136
   at APSIM.Shared.JobRunning.JobRunner.Run(IRunnable job) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 226
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 189
ERRORS FOUND!!

**Comment by par456** [comment]
> Thanks. We filled in the CN ratio and FOM, but we have new errors.
> [apsim_example_files.zip](https://github.com/user-attachments/files/17841106/apsim_example_files.zip)

I just had a look at your simulation, and as Peter said, the CN ratio and FOM are missing from the soil which is causing that error you are seeing. Once I added those in, I was able to run your sims in both windows and linux without any problem.

**Comment by lpmorenoc** [comment]
@peter-devoil @par456 Thank you for your help. As a new user of APSIM (many years as a DSSAT user and developer), does the model have the option to run simulations under water-limited conditions without specifying soil nutrient variables?

**Comment by peter-devoil** [comment]
No - that idea sank back in the '90s and some form of ceres-N has been "compulsory" since..

P

**Comment by par456** [comment]
Closing this as I think all the questions have been answered. Reopen or comment back if something was missed.
