### ISSUE TITLE
DataStore "Export to Excel" does not work

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#9510]
### What happened?

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.Packaging, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.IO.Packaging, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at ClosedXML.Excel.XLWorkbook.SetPackageProperties(OpenXmlPackage document)
   at ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, Boolean validate, Boolean evaluateFormulae)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file)
   at Utility.Excel.WriteToEXCEL(DataTable[] tables, String fileName) in APSIMNextGen\ApsimNG\Utility\Excel.cs:line 34
   at UserInterface.Presenters.ContextMenu.<>c__DisplayClass30_1.<ExportDataStoreToEXCEL>b__3() in APSIMNextGen\ApsimNG\Menus\ContextMenu.cs:line 698
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at UserInterface.Presenters.ContextMenu.ExportDataStoreToEXCEL(Object sender, EventArgs e) in APSIMNextGen\ApsimNG\Menus\ContextMenu.cs:line 701
```

### What Operating System are you on?

Windows

**Comment by par456** [comment]
Hmmm, is there something specific about that file you are working with? I just loaded, saved and run the wheat example and it was able to export to excel just fine. 

Based on the error, it seems like it was unable to write the file to the location of the apsimx file like it expected.

**Comment by BrianCollinss** [comment]
I get the same error with another file in another folder.

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.Packaging, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.IO.Packaging, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at ClosedXML.Excel.XLWorkbook.SetPackageProperties(OpenXmlPackage document)
   at ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, Boolean validate, Boolean evaluateFormulae)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file)
   at Utility.Excel.WriteToEXCEL(DataTable[] tables, String fileName) in C:\Users\U8019357\OneDrive - UniSQ\Documents\Repository\APSIMNextGen\ApsimNG\Utility\Excel.cs:line 34
   at UserInterface.Presenters.ContextMenu.<>c__DisplayClass30_1.<ExportDataStoreToEXCEL>b__3() in C:\Users\U8019357\OneDrive - UniSQ\Documents\Repository\APSIMNextGen\ApsimNG\Menus\ContextMenu.cs:line 698
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at UserInterface.Presenters.ContextMenu.ExportDataStoreToEXCEL(Object sender, EventArgs e) in C:\Users\U8019357\OneDrive - UniSQ\Documents\Repository\APSIMNextGen\ApsimNG\Menus\ContextMenu.cs:line 701
```

**Comment by ric394** [comment]
Is the file you are trying to run located within OneDrive? If so, can you try running one from your local disk?

**Comment by BrianCollinss** [comment]
I am afraid all HDD is synced to OneDrive!

**Comment by ric394** [comment]
I wasn't able to replicate this with a file sitting in OneDrive and I wasn't able to replicate it with a version of apsimx located within OneDrive either. Are you able to share the apsimx file and related resources?

**Comment by BrianCollinss** [comment]
Recent updates of VS22 fixed the issue.

**Comment by par456** [comment]
Visual studio must have been holding the file open, a bug on their end I guess. Thanks for letting us know about that.
