### ISSUE TITLE
Negative turnover

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#9564]
2003_Aug

ERROR in file: C:\aaUnderVC\Proj_RiskIndexToolFY25\r7640_RIT_Slope\CurveNumber.apsimx
Simulation name: 13088Mataikona_26a1WaterRainfedDepositionDate2003_AugSlopeRolling
Models.Core.SimulationException
 ---> Models.Core.ApsimXException:  AgPasture computed a negative tissue turnover rate
   at Models.AgPasture.PastureSpecies.EvaluateTissueTurnoverRates() in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\AgPasture\PastureSpecies.cs:line 3054
   at Models.AgPasture.PastureSpecies.OnDoPotentialPlantGrowth(Object sender, EventArgs e) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\AgPasture\PastureSpecies.cs:line 2733

**Comment by sno036** [comment]
[ErrorExample.zip](https://github.com/user-attachments/files/18204809/ErrorExample.zip)

**Comment by sno036** [comment]
Pick up debugging this next week. There are a lot of -ve digestibility values being calculated but many are not small enough to trigger that error. Look at calculateDigestibility in GenericTissue.cs as the next step.
